### ISSUE TITLE
poco.wait_for_any 导致断开连接

### ISSUE THREAD

**Issue by dzw** [AirtestProject/AirtestIDE#1044]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
Airtest IDE 1.2.13

"D:\AirtestIDE\AirtestIDE" runner "D:\auto_test\untitled.air"  --device android://127.0.0.1:5037/emulator-5554?cap_method=MINICAP&&ori_method=MINICAPORI&&touch_method=MINITOUCH --log "C:\Users\dzw\AppData\Local\Temp\AirtestIDE\scripts\38ba0ae65c8979ccbc429505530d33f2"
============================================================

[Start running..]
save log in 'C:\Users\dzw\AppData\Local\Temp\AirtestIDE\scripts\38ba0ae65c8979ccbc429505530d33f2'
[20:18:53][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 wait-for-device
[20:18:53][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[20:18:53][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\ad[20:18:54][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell monkey -p com.weile.game.buyu -c android.intent.category.LAUNCHER 1
b.exe -P 5037 -s emulator-5554 shell input keyevent HOME[20:18:55][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:14427 tcp:5001
[rpc]connected
[20:18:55][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity top
[20:18:55][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.open.pocoservice
[20:18:56][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:13187 tcp:10080
[20:18:56][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:13374 tcp:10081
[20:18:56][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap
[20:18:56][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap.so
[20:18:56][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[20:18:57][DEBUG]<airtest.core.android.cap_methods.minicap> WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.

version:5
[20:18:57][DEBUG]<airtest.core.android.cap_methods.minicap> upgrade minicap to lastest version: -1->5
[20:18:57][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell rm -r /data/local/tmp/minicap*
[20:18:57][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
[20:18:57][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.preview_sdk
[20:18:57][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release
[20:18:57][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push D:\AirtestIDE\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[20:18:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap
[20:18:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push D:\AirtestIDE\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-25/x86/minicap.so /data/local/tmp/minicap.so
[20:18:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap.so
[20:18:58][INFO]<airtest.core.android.cap_methods.minicap> minicap installation finished
[20:18:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls -l /data/local/tmp/rotationwatcher.jar
[20:18:58][DEBUG]<airtest.core.android.rotation> install_rotationwatcher skipped
[20:18:58][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell app_process -Djava.class.path=/data/local/tmp/rotationwatcher.jar /data/local/tmp com.example.rotationwatcher.Main
[20:18:59][DEBUG]<airtest.utils.nbsp> [rotation_server]b'90'
[20:18:59][INFO]<airtest.core.android.rotation> update orientation None->1
[20:18:59][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell wm size
[20:18:59][DEBUG]<airtest.core.android.cap_methods.minicap> update_rotation: 90
[20:19:00][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.sf.lcd_density
[20:19:00][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys SurfaceFlinger
[20:19:00][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getevent -p
[20:19:01][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'airtest_minicap' -P 720x1280@720x1280/90 -s
[20:19:01][DEBUG]<airtest.core.android.cap_methods.minicap> do update rotation
[20:19:01][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:17472 localabstract:minicap_17472
[20:19:01][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_17472' -P 720x1280@720x1280/90 -l 2>&1
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 18689'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 720x1280@720x1280/1'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:241) Creating SurfaceComposerClient'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:244) Performing SurfaceComposerClient init check'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:251) Creating virtual display'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:257) Creating buffer queue'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:262) Creating CPU consumer'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:266) Creating frame waiter'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:270) Publishing virtual display'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:287) Found 7.1 Developer Preview SurfaceComposerClient::setDisplaySurface'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder'
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[20:19:01][DEBUG]<airtest.core.android.cap_methods.minicap> (1, 24, 18689, 720, 1280, 720, 1280, 1, 2)
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[20:19:01][DEBUG]<airtest.core.android.cap_methods.minicap> quirk_flag found, going to resetup
[20:19:01][DEBUG]<airtest.core.android.cap_methods.minicap> minicap stream ends
[20:19:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b''
[20:19:01][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:17472
[20:19:01][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:18002 localabstract:minicap_18002
[20:19:02][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_18002' -P 1280x720@1280x720/0 -l 2>&1
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 18695'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1280x720@1280x720/0'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:241) Creating SurfaceComposerClient'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:244) Performing SurfaceComposerClient init check'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:251) Creating virtual display'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:257) Creating buffer queue'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:262) Creating CPU consumer'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:266) Creating frame waiter'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:270) Publishing virtual display'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_25.cpp:287) Found 7.1 Developer Preview SurfaceComposerClient::setDisplaySurface'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder'
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[20:19:02][DEBUG]<airtest.core.android.cap_methods.minicap> (1, 24, 18695, 1280, 720, 1280, 720, 0, 2)
[20:19:02][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[20:19:02][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "airtest\cli\runner.py", line 70, in runTest
  File "D:\auto_test\untitled.air\untitled.py", line 183, in <module>
    Login()
  File "D:\auto_test\untitled.air\untitled.py", line 59, in Login
    poco.wait_for_any([agreementTitle, btnAccount], timeout=60 * 5)
  File "D:\AirtestIDE\poco\pocofw.py", line 128, in wait_for_any
    if obj.exists():
  File "D:\AirtestIDE\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 774, in exists
    return self.attr('visible')
  File "D:\AirtestIDE\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\AirtestIDE\poco\proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "D:\AirtestIDE\poco\freezeui\hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "D:\AirtestIDE\poco\sdk\Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "D:\AirtestIDE\poco\sdk\Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "D:\AirtestIDE\poco\freezeui\hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "D:\AirtestIDE\poco\utils\simplerpc\utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "D:\AirtestIDE\poco\utils\simplerpc\simplerpc.py", line 74, in wait
    self.agent.update()
  File "D:\AirtestIDE\poco\utils\simplerpc\rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "D:\AirtestIDE\poco\utils\simplerpc\transport\tcp\main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "D:\AirtestIDE\poco\utils\simplerpc\transport\tcp\safetcp.py", line 36, in recv
    trunk = self.sock.recv(size)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。

======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 73, in runTest
  File "site-packages\six.py", line 703, in reraise
  File "airtest\cli\runner.py", line 70, in runTest
  File "D:\auto_test\untitled.air\untitled.py", line 183, in <module>
    Login()
  File "D:\auto_test\untitled.air\untitled.py", line 59, in Login
    poco.wait_for_any([agreementTitle, btnAccount], timeout=60 * 5)
  File "D:\AirtestIDE\poco\pocofw.py", line 128, in wait_for_any
    if obj.exists():
  File "D:\AirtestIDE\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 774, in exists
    return self.attr('visible')
  File "D:\AirtestIDE\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\AirtestIDE\poco\proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "D:\AirtestIDE\poco\freezeui\hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "D:\AirtestIDE\poco\sdk\Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "D:\AirtestIDE\poco\sdk\Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "D:\AirtestIDE\poco\freezeui\hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "D:\AirtestIDE\poco\utils\simplerpc\utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "D:\AirtestIDE\poco\utils\simplerpc\simplerpc.py", line 74, in wait
    self.agent.update()
  File "D:\AirtestIDE\poco\utils\simplerpc\rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "D:\AirtestIDE\poco\utils\simplerpc\transport\tcp\main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "D:\AirtestIDE\poco\utils\simplerpc\transport\tcp\safetcp.py", line 36, in recv
    trunk = self.sock.recv(size)
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。

----------------------------------------------------------------------
Ran 1 test in 9.509s

FAILED (errors=1)
[20:19:02][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:14427
[20:19:02][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:13187
[20:19:03][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:13374
[20:19:03][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:18002
[20:19:03][DEBUG]<airtest.utils.nbsp> [rotation_server]b''
[20:19:03][DEBUG]<airtest.utils.nbsp> [minicap_server]b''
[Finished]

============================================================

[20:18:53][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.weile.game.buyu
[20:18:54][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell pm clear com.weile.game.buyu

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by dzw** [comment]
agreementTitle = poco("title")
    btnAccount = poco("btn_account")
    poco.wait_for_any([agreementTitle, btnAccount], timeout=60 * 5)
    poco("btn_ok").click()
