### ISSUE TITLE
无法连接三星GALAXY S4 I959

### ISSUE THREAD

**Issue by dhpls** [AirtestProject/AirtestIDE#108]
在Airtest IDE里点击connect，返回“ADB指令执行失败，请查阅官网[FAQ]获得更多信息"

具体log如下：

('Last opened scripts:', [u'C:\\Users\\alina\\AppData\\Local\\Temp\\AirtestIDE\\Scripts\\untitled.air'])
[02:30:28][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 4d0043e16b865065 wait-for-device
[02:30:28][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 4d0043e16b865065 shell getprop ro.build.version.sdk
[02:30:28][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 4d0043e16b865065 shell ls /data/local/tmp/minicap ; echo ---$?---
[02:30:29][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 4d0043e16b865065 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[02:30:29][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 4d0043e16b865065 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[02:30:29][DEBUG]<airtest.core.android.minicap> version:5
[02:30:29][DEBUG]<airtest.core.android.minicap> skip install minicap
[02:30:29][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 4d0043e16b865065 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 167, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 77, in __init__
  File "app\plugins\device\android\android_phone.py", line 103, in _initDev
  File "airtest\core\android\android.py", line 463, in display_info
  File "airtest\core\android\android.py", line 475, in get_display_info
  File "airtest\utils\snippet.py", line 101, in ready_func
  File "airtest\core\android\minicap.py", line 134, in get_display_info
  File "airtest\core\android\adb.py", line 345, in shell
AdbShellError: stdout[] stderr[Segmentation fault
]
[02:30:39][ERROR]<airtest> None
[02:30:40][DEBUG]<airtest.core.android.adb> E:\AirtestIDE_2018-05-09_16\airtest\core\android\static\adb\windows\adb.exe devices

**Comment by Meteorix** [comment]
这是设备不兼容minicap，下周回放出一个可选项

**Comment by rockywhisper** [comment]
@dhpls  你好，请在连接前把这个选项勾选上即可connect成功：

![image](https://user-images.githubusercontent.com/8188879/41468079-492be8bc-70db-11e8-92d4-b9c9a7a7839c.png)


另外，我们今天发布了稳定预览版本，下载链接：http://airtest.netease.com/changelog.html

欢迎试用，有问题随时反馈哈，感谢  : )
