### ISSUE TITLE
check_app()报错

### ISSUE THREAD

**Issue by FeiYuPro** [AirtestProject/AirtestIDE#1115]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
name 'check_app' is not defined
**复现步骤：**
![image](https://github.com/AirtestProject/AirtestIDE/assets/80089751/3bbdc524-714b-4075-92f2-bc9f899ba1d3)
![image](https://github.com/AirtestProject/AirtestIDE/assets/80089751/8d462942-cae8-44dd-845f-dc25239ee27f)
![image](https://github.com/AirtestProject/AirtestIDE/assets/80089751/43a7dc4f-0082-477c-82a2-244aa899817a)

**python 版本:** `python3.x`
python3.9
**操作系统:** `Windows7 64bit`
win11
**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.15

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

**Comment by yimelia** [comment]
```
dev = device()
dev.check_app()
```

**Comment by FeiYuPro** [comment]
使用
dev = device()
dev.check_app()

PACKAGE_NAME = "com.dygame.longjiegame.cs.nw.dl.pkq"
dev = device()
dev.check_app(PACKAGE_NAME)

当应用不存在的时候 报错误 
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.product.model
内部型号:DVC-AN20
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.product.brand
手机品牌:HUAWEI
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.product.name
手机名称:DVC-AN20
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.product.manufacturer
手机制造商:HUAWEI
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.build.version.sdk
Android等级:29
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.build.version.release
Android版本:10
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell dumpsys package com.dygame.longjiegame.cs.nw.dl.pkq
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell ls /data/local/tmp/minicap
[12:03:56][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell ls /data/local/tmp/minicap.so
[12:03:57][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[12:03:57][DEBUG]<airtest.core.android.cap_methods.minicap> version:5
[12:03:57][DEBUG]<airtest.core.android.cap_methods.minicap> skip install minicap
[12:03:57][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell ls -l /data/local/tmp/rotationwatcher.jar
[12:03:57][DEBUG]<airtest.core.android.rotation> install_rotationwatcher skipped
[12:03:57][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell app_process -Djava.class.path=/data/local/tmp/rotationwatcher.jar /data/local/tmp com.example.rotationwatcher.Main
[12:03:57][DEBUG]<airtest.utils.nbsp> [rotation_server]b'0'
[12:03:58][INFO]<airtest.core.android.rotation> update orientation None->0
[12:03:58][DEBUG]<airtest.core.android.cap_methods.minicap> update_rotation: 0
[12:03:58][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell wm size
[12:03:58][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getprop ro.sf.lcd_density
[12:03:58][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell dumpsys SurfaceFlinger
[12:03:58][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell getevent -p
[12:03:58][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'airtest_minicap' -P 1080x2400@1080x2400/0 -s
[12:03:59][DEBUG]<airtest.core.android.cap_methods.minicap> do update rotation
[12:03:59][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 forward --no-rebind tcp:15351 localabstract:minicap_15351
[12:03:59][DEBUG]<airtest.core.android.adb> E:\work\AirIDE\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s Q2NVB20612019315 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_15351' -P 1080x2400@1080x2400/0 -l 2>&1
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 22537'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2400@1080x2400/0'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 7835652 bytes for JPG encoder'
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[12:03:59][DEBUG]<airtest.core.android.cap_methods.minicap> (1, 24, 22537, 1080, 2400, 1080, 2400, 0, 2)
[12:03:59][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[12:03:59][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "airtest\cli\runner.py", line 72, in runTest
  File "C:\Users\Administrator\Desktop\bat\100server.air\100server.py", line 87, in <module>
    dev.check_app(PACKAGE_NAME)
  File "airtest\core\android\android.py", line 306, in check_app
  File "airtest\core\android\adb.py", line 1338, in check_app
airtest.core.error.AirtestError: 'package "com.dygame.longjiegame.cs.nw.dl.pkq" not found'
