### ISSUE TITLE
oppo connect异常

### ISSUE THREAD

**Issue by kogel-net** [AirtestProject/AirtestIDE#1118]
**详细描述问题bug：**
bug描述

[15:36:40][DEBUG]<airtest.core.android.adb> D:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 8c5e6ae8 shell dumpsys activity top
Traceback (most recent call last):
  File "app\plugins\poco\poco_probe.py", line 296, in initPoco
  File "D:\Program Files\AirtestIDE\poco\drivers\android\uiautomation.py", line 165, in __init__
    current_top_activity_package = self.device.get_top_activity_name()
  File "airtest\core\android\android.py", line 662, in get_top_activity_name
    tanp = self.get_top_activity()
  File "airtest\core\android\android.py", line 652, in get_top_activity
    return self.adb.get_top_activity()
  File "airtest\core\android\adb.py", line 1172, in get_top_activity
    dat = self.shell('dumpsys activity top')
  File "airtest\core\android\adb.py", line 374, in shell
    out = self.raw_shell(cmd)
  File "airtest\core\android\adb.py", line 332, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "airtest\core\android\adb.py", line 195, in cmd
    raise DeviceConnectionError(stderr)
airtest.core.error.DeviceConnectionError: b"error: device '8c5e6ae8' not found\r\n"

**复现步骤：**
点击connect报错, 三个connect选项都尝试过

**python 版本:** `python3.x`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号: oppo r9
 - Android系统版本号: [e.g. Android 13]
 - (别的信息) USB调试，禁止权限监控，输入法和权限都已设置

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：v1.2.15

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://github.com/AirtestProject/AirtestIDE/assets/42330679/0ddce34a-ac02-4783-a74f-2052a12c4be5)

**Comment by yimelia** [comment]
需要确认手机是否正确显示在了设备列表中，且状态是device
也就是说，需要确认 `adb devices`命令行的执行结果是能够看到这台手机，并且状态为device
