### ISSUE TITLE
Mac下编辑本地Python路径后，运行报错（确认路径正确，ide版本v1.2.15)

### ISSUE THREAD

**Issue by YeungHoiChiu** [AirtestProject/AirtestIDE#1125]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述

**复现步骤：**

**python 版本:** `python3.10.12`

**操作系统:** `M1 Pro Mac os 14`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：v1.2.15

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
<img width="788" alt="image" src="https://github.com/AirtestProject/AirtestIDE/assets/44832826/0214fa09-b402-46a0-9d0c-a6941f2386f8">

**Comment by YeungHoiChiu** [comment]
============================================================

[Start running..]
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): tried: '/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (no such file), '/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/bin/python3.10"
  * The NumPy version is: "1.26.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): tried: '/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (no such file), '/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/AirtestIDE.app/Contents/MacOS/sample/custom_launcher.py", line 7, in <module>
    from airtest.cli.runner import run_script
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/airtest/cli/runner.py", line 12, in <module>

    from airtest.core.api import G, auto_setup, log
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/airtest/core/api.py", line 8, in <module>
    from airtest.core.cv import Template, loop_find, try_log_screen
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/airtest/core/cv.py", line 13, in <module>
    from airtest import aircv
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/airtest/aircv/__init__.py", line 1, in <module>
    from .aircv import *  # noqa
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/airtest/aircv/aircv.py", line 5, in <module>
    import cv2
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/cv2/__init__.py", line 11, in <module>
    import numpy
  File "/Users/kamiyeung/.local/share/virtualenvs/Pytest_Allure_Airtest-baQG2VD3/lib/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[Finished]

============================================================

**Comment by YeungHoiChiu** [comment]
尝试过使用非虚拟环境的本地python也是一样的报错。。

**Comment by YeungHoiChiu** [comment]
已解决，是由于arm平台指令和x86不一样，在ide中使用的话，似乎都是用的x86的那一套，解决方法是在命令行临时修改成x86模式再去创建虚拟环境以及下载x86的python依赖包，在ide中设置python路径指向该虚拟环境即可
<img width="573" alt="image" src="https://github.com/AirtestProject/AirtestIDE/assets/44832826/2c4db99a-bd70-41ec-990b-65e2b671da33">
