### ISSUE TITLE
IDE启动失败

### ISSUE THREAD

**Issue by deardy** [AirtestProject/AirtestIDE#1154]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
IDE启动不了

**复现步骤：**
双击 AirtestIDE.exe，闪退

**python 版本:** `python3.x`
python3.9.11
**操作系统:** `Windows7 64bit`
Windows7 64bit
**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.17

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

log：

d:\AirtestIDE>AirtestIDE.exe
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : C:\Users\Administrator\AppData\Local\AirtestIDE\AirtestIDE\user.json
[18976:21240:0425/131112.626:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
Traceback (most recent call last):
  File "jedi\cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\parso\grammar.py", line 236, in load_grammar
KeyError: 'd:\\AirtestIDE\\parso\\python\\grammar39.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\parso\grammar.py", line 239, in load_grammar
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\AirtestIDE\\parso\\python\\grammar39.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\editor\plugin.py", line 241, in init_jedi_env
  File "jedi\api\__init__.py", line 494, in preload_module
    Script(s, 1, len(s), None, environment=environment).completions()
  File "jedi\api\__init__.py", line 108, in __init__
    project, environment=environment, script_path=self.path
  File "jedi\evaluate\__init__.py", line 95, in __init__
    self.grammar = environment.get_grammar()
  File "jedi\cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "jedi\api\environment.py", line 36, in get_grammar
    return parso.load_grammar(version=version_string)
  File "site-packages\parso\grammar.py", line 250, in load_grammar
  File "site-packages\parso\grammar.py", line 246, in load_grammar
NotImplementedError: Python version 3.9 is currently not supported.

ARB::createContext: wglCreateContextAttribsARB() failed (GL error code: 0x0) for format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)), shared context: 0x1 (操作成功完成。)
GDI::createContext: wglCreateContext failed. (操作成功完成。)
Unable to create a GL Context.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.

**Comment by deardy** [comment]
Fixed. Remove C:\Users\Administrator\AppData\Local\AirtestIDE\，it's ok!
