### ISSUE TITLE
UI对象找不到到，不会被记录的报告log中。。。

### ISSUE THREAD

**Issue by IvyyLu** [AirtestProject/AirtestIDE#120]
UI对象找不到到，不会被记录的报告log中。。。

```
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 88, in runTest
  File "F:\wwddzAutoTest\src\test.air\test.py", line 19, in <module>
    poco("store_btn_back1").click()
  File "poco\proxy.py", line 29, in wrapped
PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "store_btn_back1"
```

**Comment by zzldjkzxf** [comment]
@IvyyLu 目前poco报错已经能在报告中看到了哈。
