### ISSUE TITLE
win10下使用snapshot或者assert exit去截图应用直接闪退

### ISSUE THREAD

**Issue by AlanFightting** [AirtestProject/AirtestIDE#129]
环境：
win10 x64
Airtest IDE v0.0.19

使用snapshot或者assert exit类型的去截图直接闪退

 New client connection'
Traceback (most recent call last):
  File "app\plugins\editor\plugin.py", line 344, in insertCode
  File "app\plugins\editor\tab_editor.py", line 474, in insertCode
  File "app\plugins\editor\tab_editor.py", line 882, in trans_script_to_html
  File "app\utils.py", line 45, in custom_decode
  File "encodings\utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-19: ordinal not in range(128)

**Comment by yimelia** [comment]
@AlanFightting 你好，抱歉这是最新版本IDE的问题，我们会尽快放出修复后的版本，目前暂时可以先使用上一个版本的IDE

**Comment by rockywhisper** [comment]
@AlanFightting  Hi, 新版本已经发布，下载链接详见：  http://airtest.netease.com/changelog.html
该问题应该已经解决，欢迎下载试用哈    : )
