### ISSUE TITLE
使用assert_exits和assert_not_exits功能时IDE闪退

### ISSUE THREAD

**Issue by oukae** [AirtestProject/AirtestIDE#144]
**版本号:**
AirtestIDE:v0.0.19
**步骤:**

1. 连接android真机
2. 使用assert_exits或assert_not_exits功能进行录制脚本

**期望结果:**
脚本录制成功
**实际结果:**
IDE闪退

**errorlog:**
?---
[03:00:04][INFO]<airtest.core.android.rotation> update orientation None->1
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell dumpsys display
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_17
038' -P 1920x1080@800x450/0 -l 2>&1
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell dumpsys SurfaceFlinger ; echo ---$?---
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'PID: 24416'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: Using projection 1920x1080@800x450/0'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:247) Creating SurfaceComposerClient'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:250) Performing SurfaceComposerClient init check'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:257) Creating virtual display'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:263) Creating buffer queue'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:268) Creating CPU consumer'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:272) Creating frame waiter'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_22.cpp
:276) Publishing virtual display'
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell getevent -p ; echo ---$?---
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocat
ing 6268932 bytes for JPG encoder'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (/home/lxn3032/minicap_for_ide/jni/mini
cap/minicap.cpp:473) Server start'
[03:00:04][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (/home/lxn3032/minicap_for_ide/jni/mini
cap/minicap.cpp:475) New client connection'
[03:00:04][DEBUG]<airtest.core.android.minicap> (1, 24, 24416, 1920, 1080, 800, 450, 0, 2)
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell getprop ro.product.cpu.abi
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell getprop ro.build.version.sdk
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell ls /data/local/tmp/minitouch ; echo ---$?---
[03:00:04][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell ls -l /data/local/tmp/minitouch ; echo ---$?---
[03:00:04][DEBUG]<airtest.core.android.minitouch> install_minitouch skipped
[03:00:05][DEBUG]<airtest.core.android.minicap> update_rotation: 90
[03:00:05][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 forward --no-rebind tcp:13475 localabstract:minitouch_13475
[03:00:05][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell /data/local/tmp/minitouch -n 'minitouch_13475' 2>&1
[03:00:05][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Note: device /dev/input/mouse0 is not suppo
rted by libevdev'
[03:00:06][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Note: device /dev/input/mice is not support
ed by libevdev'
[03:00:06][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Note: device /dev/input/event1 was outscore
d by /dev/input/event0 (22449 >= 11440)'
[03:00:06][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Type B touch device synaptics_dsx_i2c (1080
x1920 with 10 contacts) detected on /dev/input/event0 (score 22449)'
[03:00:06][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Connection established'
[03:00:06][DEBUG]<airtest.core.android.minitouch> minitouch header:'v 1\n^ 10 1080 1920 0\n$ 24438\n
'
[03:00:18][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$
?---
[03:00:18][DEBUG]<airtest.core.android.adb> E:\AIRTES~3\airtest\core\android\static\adb\windows\adb.
exe -P 5037 -s 5f51eef2 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'airtest_mi
nicap' -P 1920x1080@1920x1080/0 -s
Traceback (most recent call last):
  File "app\plugins\editor\plugin.py", line 344, in insertCode
  File "app\plugins\editor\tab_editor.py", line 474, in insertCode
  File "app\plugins\editor\tab_editor.py", line 882, in trans_script_to_html
  File "app\utils.py", line 45, in custom_decode
  File "encodings\utf_8.py", line 16, in decode
UnicodeEncodeError: 'ascii' codec can't encode characters in position 102-107: ordinal not in range(
128)

**Comment by rockywhisper** [comment]
@oukae  Hi, 新的稳定版预览版本已经发布啦，问题已经解决了。

下载链接详见： http://airtest.netease.com/changelog.html
如果遇到问题还请及时反馈，感谢。 : )
