### ISSUE TITLE
device_platform 在Airtestcase初始化之前不能获取到设备，为None

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#163]
v0.1.1 测试IOS出现，测试Android没有。

**Comment by suyuchen123** [comment]
可以提供一下出错是 执行了具体什么样的脚本呢？

**Comment by StandOutstar** [comment]
在启动器里的CustomAirtestCase定义前，获取device_platform，log窗口里看到传入了ios device，但实际结果：
Current test platform: NoneType
[24141] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/AirtestIDE.py", line 66, in <module>
  File "/Users/wjjn3033/dev/idestable/airtest-ide/AirtestIDE.py", line 60, in main
  File "<string>", line 29, in <module>
AttributeError: 'NoneType' object has no attribute 'uuid'
![image](https://user-images.githubusercontent.com/17442044/41841037-d6dad61c-7899-11e8-9821-4bd720c7787e.png)

**Comment by Meteorix** [comment]
这个时候还没有初始化G.DEVICE，当然就获取不到，你可以看看AirtestCase的代码，在setupClass中初始化的
