### ISSUE TITLE
文件被外部更改后提示重新加载，点击yes后，界面无响应，随后界面自动退出

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#165]
v0.1.1 win10
 log窗口中的部分日志：
Traceback (most recent call last):
  File "app\plugins\editor\tab_editor.py", line 697, in addModifiedFiles
  File "app\plugins\editor\tab_editor.py", line 713, in isFileModified
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 1285: illegal multibyte sequence

**Comment by yimelia** [comment]
@StandOutstar 抱歉，确实是有点问题，感谢反馈，这个BUG我们会尽快修正

**Comment by yimelia** [comment]
这个问题在最新版本已经修正，预计6.26号会发出新版

**Comment by suyuchen123** [comment]
fixed，check http://airtest.netease.com/changelog.html
