### ISSUE TITLE
assert_not_exists 直接返回图片存在，实际不存在，报告中也没有看到存在，现在等于这个api只会返回有错

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/AirtestIDE#167]
版本：v0.1.1 on MAC
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 78, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/helper.py", line 130, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 483, in assert_not_exists
AssertionError: Template(/Users/mac/Nustore Files/3C_APP_TEST_PROJECT/project_commons/commons.air/tpl1529484948412.png) exists unexpectedly at pos: (228, 1332), message:某个操作

**Comment by StandOutstar** [comment]
通过其他用例发现，可能跟图片有关，可能重新选取图片后，就恢复了。

**Comment by Meteorix** [comment]
ok 多谢反馈

**Comment by StandOutstar** [comment]
希望assert_not_exists 在报找到图片时，在报告中也可以绘制出线框
