### ISSUE TITLE
android设备无法接收任何触屏事件，都报错

### ISSUE THREAD

**Issue by whhema** [AirtestProject/AirtestIDE#190]
脚本如下（基本是初始化的脚本）：
# -*- encoding=utf8 -*-
__author__ = "xxxx"

from airtest.core.api import *

auto_setup(__file__)

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco()

touch(Template(file:///var/folders/gx/g377hhs52t393rbvs43t29v80000gn/T/AirtestIDE/Scripts/untitled.air/tpl1530797427511.png, record_pos=(-0.222, -0.061), resolution=(1920, 1200)))

==============================
log如下：
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/var/folders/gx/g377hhs52t393rbvs43t29v80000gn/T/AirtestIDE/Scripts/untitled.air/untitled.py", line 12, in <module>
    touch(Template(file:///var/folders/gx/g377hhs52t393rbvs43t29v80000gn/T/AirtestIDE/Scripts/untitled.air/tpl1530797427511.png", record_pos=(-0.222, -0.061), resolution=(1920, 1200)))
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 261, in touch
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/android.py", line 290, in touch
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/snippet.py", line 104, in ready_func
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/snippet.py", line 115, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minitouch.py", line 51, in install_and_setup
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minitouch.py", line 145, in setup_server
RuntimeError: minitouch setup timeout

----------------------------------------------------------------------
Ran 1 test in 10.905s

FAILED (errors=1)
[09:30:41][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s d383f085 forward --remove tcp:19451
[09:30:41][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s d383f085 forward --remove tcp:15472
[09:30:41][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s d383f085 forward --remove tcp:12101
[09:30:41][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s d383f085 forward --remove tcp:17814
[09:30:41][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
[Finished]

============================================================

**Comment by whhema** [comment]
ps: 把touch换成swipe，也是一样的错误： minitouch setup timeout

我手头的android设备的rom是被定制过的，如果需要rom的某些功能作为支撑前提，请告知我，谢谢。

**Comment by Meteorix** [comment]
IDE里面也不能操作吗？

**Comment by rockywhisper** [comment]
@whhema  Hi，请问使用[AirtestIDE](http://airtest.netease.com/)是否可以正常连接设备？
如果不能，请优先确认 [设备的开发者选项设置问题](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/5_faq/2_android_faq.html#id9)

欢迎随时反馈~

**Comment by whhema** [comment]
@rockywhisper IDE可以正常连接设备，也可以在IDE中，看到设备桌面的内容。

**Comment by yimelia** [comment]
@whhema IDE连上后，能否用鼠标进行操作？方便的话可以告知一下设备型号我们试试。如果不行的话，在连接设备时的connect下拉菜单勾选 `Use ADB touch` 再connect即可，对应地，命令行的连接字符串里也要加上 `ori_method=ADBORI` 这个配置，具体可以查看 命令行运行脚本的[帮助文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html)里的 **部分安卓设备的特殊参数** 章节。
