### ISSUE TITLE
安卓模拟器连接提示ADB指令执行失败

### ISSUE THREAD

**Issue by nmk4** [AirtestProject/AirtestIDE#209]
用的是Android studio的模拟器，nexus5x api27.

**Comment by nmk4** [comment]
[11:42:53][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 wait-for-device
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[11:42:58][WARNING]<airtest.core.api> Device:emulator-5554 updated <airtest.core.android.android.Android object at 0x000001DD24632E48> -> <airtest.core.android.android.Android object at 0x000001DD252C8CF8>
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap.so
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[11:42:58][ERROR]<airtest.core.android.minicap> stdout[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": "/data/local/tmp/minicap" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)\r\nAborted \r\n'] stderr[b'']
[11:42:58][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->5
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell rm /data/local/tmp/minicap*
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.preview_sdk
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push C:\Program Files\AirtestIDE\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push C:\Program Files\AirtestIDE\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-27/x86/minicap.so /data/local/tmp/minicap.so
[11:42:58][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap.so
[11:42:59][INFO]<airtest.core.android.minicap> minicap installation finished
[11:42:59][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
Traceback (most recent call last):
  File "airtest\core\android\adb.py", line 368, in shell
  File "airtest\core\android\adb.py", line 326, in raw_shell
  File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": "/data/local/tmp/minicap" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)\r\nAborted \r\n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 153, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 75, in __init__
  File "app\plugins\device\android\android_phone.py", line 101, in _initDev
  File "airtest\core\android\android.py", line 507, in display_info
  File "airtest\core\android\android.py", line 526, in get_display_info
  File "airtest\utils\snippet.py", line 106, in ready_func
  File "airtest\core\android\minicap.py", line 135, in get_display_info
  File "airtest\core\android\adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": "/data/local/tmp/minicap" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)\r\nAborted \r\n']
[11:42:59][ERROR]<airtest> None
[11:42:59][DEBUG]<airtest.core.android.adb> C:\Program Files\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices

**Comment by shmily-cwt** [comment]
你看下本地是否有运行其他手机助手（进程杀掉或者卸载手机助手），或者安装Android SDK查看adb.exe和Airtest adb.exe版本是否一致。如果不一致就替换一个保持版本一致，如果还不行，i 也不晓得了。

**Comment by yimelia** [comment]
请查阅文档 [模拟器连接](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/2_device_connection/2_emulator_connection.html) 章节，模拟器连接时可以尝试勾选connect下拉按钮中的`javacap`选项，然后再尝试点connect连接。
如果不行的话，可以尝试换一个API版本模拟器，或者是尝试诸如夜神等其他模拟器软件

**Comment by Sposito** [comment]
I am still having the same problem here, changed versions, reinstalled adb, nothing works

```
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 wait-for-device
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap
install minicap
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.preview_sdk
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 push /usr/lib/airtest/core/android/static/stf_libs/x86/minicap /data/local/tmp/minicap
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 push /usr/lib/airtest/core/android/static/stf_libs/minicap-shared/aosp/libs/android-24/x86/minicap.so /data/local/tmp/minicap.so
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap.so
minicap installation finished
/usr/lib/airtest/core/android/static/adb/linux/adb -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
Traceback (most recent call last):
  File "airtest/core/android/adb.py", line 368, in shell
  File "airtest/core/android/adb.py", line 326, in raw_shell
  File "airtest/core/android/adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": /data/local/tmp/minicap: has text relocations\nAborted \n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app/plugins/device/android/android_client.py", line 161, in loadConnectedPhones
  File "app/plugins/device/android/android_phone.py", line 80, in __init__
  File "app/plugins/device/android/android_phone.py", line 106, in _initDev
  File "airtest/core/android/android.py", line 517, in display_info
  File "airtest/core/android/android.py", line 536, in get_display_info
  File "airtest/utils/snippet.py", line 106, in ready_func
  File "airtest/core/android/minicap.py", line 135, in get_display_info
  File "airtest/core/android/adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": /data/local/tmp/minicap: has text relocations\nAborted \n']

Failed to execute ADB commands, please read [Docs](http://airtest.netease.com/docs/en/3_faq/android_connection.html)
```

**Comment by yimelia** [comment]
hi @Sposito , see [this](http://airtest.netease.com/docs/en/3_faq/android_connection_new.html#support-issues-for-other-smart-devices), check the `use JAVACAP` and `Use ADB orientation` and try again :)

**Comment by srishenoy** [comment]
How can we install javacap, ADB orientation & add touch using python??
