### ISSUE TITLE
OPPO系列手机只能连接，不能显示UI元素列表（AirtestIDE_2018-05-22_18，这个版本还能显示UI列表），之后更新版本不能正常显示

### ISSUE THREAD

**Issue by kfkvkkr** [AirtestProject/AirtestIDE#233]
**复现步骤**
1. 连接OPPO手机（R15,A3）
2. 连接OPPO手机（提示安装软件成功）
3. 观察左边UI渲染树无效果无法显示

**预期效果**
(左边UI渲染树显示UI元素)

**python 版本:** `python2.7`

**操作系统:** `Windows10 64bit`

**设备:**  OPPO 
 - 型号: [PADM00]
 - 系统: [Android 8.1]
 - (别的信息)

**其他相关环境信息**
(AirtestIDE_2018-05-22_18版本上运行正常。)
```
[05:47:07][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-09-05_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s TWUSH6ORU85SUSS4 shell dumpsys activity top
[05:47:07][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-09-05_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s TWUSH6ORU85SUSS4 shell dumpsys package com.netease.nie.yosemite
[05:47:07][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[05:47:07][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-09-05_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s TWUSH6ORU85SUSS4 shell settings get secure default_input_method
[05:47:07][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-09-05_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s TWUSH6ORU85SUSS4 shell ime list -a
[05:47:08][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-09-05_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s TWUSH6ORU85SUSS4 shell ime enable com.netease.nie.yosemite/.ime.ImeService
Traceback (most recent call last):
  File "airtest\core\android\adb.py", line 368, in shell
  File "airtest\core\android\adb.py", line 326, in raw_shell
  File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'']

During handling of the above exception, another exception occurred:
```

**Comment by yimelia** [comment]
@kfkvkkr hi，我试了一下这台手机，可能是因为OPPO系列的手机在通过usb安装应用时，部分机型需要输入密码，但是由于在AirtestIDE中是自动安装的，因此这个步骤可能会有些问题。
可以试一下这样操作： 在`AirtestIDE\airtest\core\android\static\apks`目录下找到一个叫做`Yosemite.apk`的应用，将它手工安装到你的手机中，安装完毕之后再使用AirtestIDE做启动poco/运行输入的操作。

**Comment by yimelia** [comment]
安装完毕后，可能还需要在系统设置-输入法中，将Yosemite输入法设为默认输入法，然后才能继续执行。
