### ISSUE TITLE
写好airtest脚本后，用firebase生成测试APK放进模拟器里，敲完adb命令报错，不太看得懂，求帮助

### ISSUE THREAD

**Issue by 742619648** [AirtestProject/AirtestIDE#240]
```
C:\Users\win10>adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

org.kivy.android.ExampleInstrumentedTest:
Process crashed while executing launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
        at org.libsdl.app.SDLActivity.nativeSetEnv(Native Method)
        at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:169)
        at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:116)
        at android.os.AsyncTask.finish(AsyncTask.java:632)
        at android.os.AsyncTask.access$600(AsyncTask.java:177)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
INSTRUMENTATION_RESULT: shortMsg=java.lang.UnsatisfiedLinkError
INSTRUMENTATION_RESULT: longMsg=java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
INSTRUMENTATION_CODE: 0
```

**Comment by zzldjkzxf** [comment]
@742619648  可以报一下手机型号吗，这个可能是因为android版本太低的原因

**Comment by 742619648** [comment]
用的是夜神模拟器安卓4.4.2，我换了夜神模拟器的安卓5.1.1版本还是不行，另一种报错
Time: 8.165
There was 1 failure:
1) launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest)
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 81, in test
  File "/data/data/com.netease.open.airbase/files/app/auto_sendmessage.air/auto_sendmessage.py", line 16
SyntaxError: Non-ASCII character '\xe6' in file /data/data/com.netease.open.airbase/files/app/auto_sendmessage.air/auto_sendmessage.py on line 16, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)

FAILURES!!!
Tests run: 1,  Failures: 1

**Comment by zzldjkzxf** [comment]
@742619648 看起来是你的脚本中有特殊字符，把脚本里的中文删掉试试？

**Comment by 742619648** [comment]
这次好像说我少了库...

Time: 8.641
There was 1 failure:
1) launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest)
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 81, in test
  File "/data/data/com.netease.open.airbase/files/app/auto_sendmessage.air/auto_sendmessage.py", line 3, in <module>
    from poco.drivers.std import StdPoco
  File "copy_app/poco\__init__.py", line 3, in <module>
  File "copy_app/poco\pocofw.py", line 8, in <module>
  File "copy_app/poco\acceleration.py", line 7, in <module>
  File "copy_app/poco\exceptions.py", line 4, in <module>
ImportError: No module named six

**Comment by zzldjkzxf** [comment]
@742619648  是这样的，目前firebase还不支持android应用的标准poco。只支持airtest模块。游戏接了poco的话可以是支持的

**Comment by 742619648** [comment]
游戏是接了poco库的，我可以在airtest里面用poco库定位控件，难道生成apk是不支持poco库的吗

**Comment by zzldjkzxf** [comment]
噢，你是用的stdpoco对吧。不好意思我看错了，那确实是我们这里少打了库进去。谢谢你的反馈，这是个bug，我们会尽快修复。

**Comment by yimelia** [comment]
@742619648 可以看一下你用pyinstaller的命令行是怎么打包的么，打的是什么内容？

**Comment by rockywhisper** [comment]
@742619648  
首先，你需要先了解一下airtest代码中的脚本运行的响应代码：https://github.com/AirtestProject/Airtest/blob/c209b2341da576e69a0ac7fb2053cc31054edb25/airtest/cli/__main__.py#L14

 1、 可以看出，只需要把对应的命令行参数传入airtest内就可以正常运行。
 2、 但是我不知道你是怎么进行的封装打包，中间是否牵涉到命令行参数的自定义传递，所以没法给你完整的运行指令。
3、 实际上打包出来的exe里面是有你打进去的python&airtest环境的。

假设你直接打包了`Airtest/airtest/cli/__main__.py`这个文件，打包成了xxx.exe，可以直接用`xxx.exe run my_script.air`这样来运行，此时命令行参数会直接传递给__main__.py执行运行逻辑。

如果你在外面自己写了一个项目壳，项目内import了airtest，使用pyinstaller对这个项目进行了打包，那么你需要自己在项目中主动进行参数传递，这个就是你自己的项目逻辑层面，可以自己把握。

**Comment by 742619648** [comment]
我是打包了一个tkinter库编写的界面，主要功能是点击按钮在cmd中运行airtest脚本
 os.popen('python -m airtest run '+ path +' --device '+ device + method)
启用命令行后，提示没有airtest，换成python起头，就提示没有python

**Comment by rockywhisper** [comment]
@742619648  如果只是这个功能，那就好办了，你可以直接把python路径写完整就是了。

案例：`os.popen("C:\Python27\python.exe -m pip list")`

**Comment by 742619648** [comment]
发给其他没有python环境的人也能这么写吗

**Comment by rockywhisper** [comment]
@742619648  不能.. 这种情况直接用AirtestIDE不就行了么..  :-)

**Comment by 742619648** [comment]
就是想打包自己写好的airtest脚本给其他没有搭过环境的人用，还有另一个问题，要运行airtest脚本，必须要使用xxx.air这个文件夹吗，有没有什么写法能绕过去直接用里面的.py文件？

**Comment by 742619648** [comment]
目前我就知道通过cmd运行airtest脚本，因此就准备2个文件，一个写了启用cmd运行airtest命令的.py文件，和一个已经写好了的xxx.air脚本，这里之后应该怎么打包，或者怎么修改才能发给其他无环境的人使用

**Comment by rockywhisper** [comment]
@742619648  
1、如果只是想给其他没有搭过环境的人用，你可以调用AirtestIDE.exe运行脚本就好，[详见教程](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#airtestide) 。至于你是通过`bat`调用，还是`os.popen()`调用都没有问题的。

2、如果你使用的是airtest图像脚本的话，air文件夹里面包含了图片资源，所以需要文件夹。如果你是纯poco的python脚本，没有图片资源的话，那就是一个纯python脚本。
事实上你也是可以直接运行 xx.air/xx.py的，脚本模板中的`auto_setup(__file__)`会在运行脚本时尝试自动连接设备，图片资源也会默认使用同级目录下的。

**Comment by 742619648** [comment]
原来可以这么运行的啊，之前因为start_app()这个函数运行不了，我以为只能通过airtest运行，注释掉之后，发现可以运行成功，好像有点豁然开朗了，接下来只要把界面加进去，直接打包成exe文件，应该就能成了，poco库里面没有启动app的函数吗

**Comment by rockywhisper** [comment]
@742619648  似乎没有遇到过`start_app()`运行不了的情况。

就运行脚本来说，因为airtest也就是个python库，你完全可以写一个2行的python脚本运行，可以不用文件夹的束缚：
``` python
from airtest.core.api import *
start_app("xxxx.xx.package")
```

**Comment by 742619648** [comment]
是这样一个报错
Traceback (most recent call last):
  File "E:\send.air\send.py", line 92, in <module>
    run()
  File "E:\send.air\send.py", line 31, in run
    start_app(yeshen) #启动APP
  File "D:\Python\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Python\lib\site-packages\airtest\core\api.py", line 146, in start_app
    G.DEVICE.start_app(package, activity)
AttributeError: 'NoneType' object has no attribute 'start_app'

**Comment by 742619648** [comment]
airtest脚本用pyinstaller打包之后报错
[04:46:23][DEBUG]<airtest.core.android.adb> C:\Users\win10\AppData\Local\Temp\_MEI93962\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:62001 get-state
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "autoSendmessage.py", line 113, in cmds
  File "autoScript.py", line 18, in autoRun
  File "site-packages\airtest\core\api.py", line 62, in connect_device
  File "site-packages\airtest\core\api.py", line 32, in init_device
  File "site-packages\airtest\core\android\android.py", line 38, in __init__
  File "site-packages\airtest\core\android\adb.py", line 40, in __init__
  File "site-packages\airtest\core\android\adb.py", line 237, in connect
  File "site-packages\airtest\core\android\adb.py", line 263, in get_status
  File "site-packages\airtest\core\android\adb.py", line 151, in start_cmd
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by rockywhisper** [comment]
@742619648 你好，建议你的程序通过调用`AirtestIDE.exe runner ...`指令来执行脚本。

**Comment by 742619648** [comment]
我找到问题的源头了，pyinstaller打包的时候没有把airtest和poco库带进去，手动添加就正常了，不过为什么会这样呢？

**Comment by 742619648** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "E:\auto\autoSendmessage.py", line 108, in cmds
    autoScript.autoRun(self.config, self.package, self.devices)
  File "E:\auto\autoScript.py", line 29, in autoRun
    poco("btn_5").wait(5).click()                             #没输入值，就直接点登录按钮
  File "D:\Python\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\Python\lib\site-packages\poco\proxy.py", line 285, in click
    ret = self.poco.click(pos_in_percentage)
  File "D:\Python\lib\site-packages\poco\pocofw.py", line 248, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "D:\Python\lib\site-packages\poco\utils\airtest\input.py", line 60, in click
    pw, ph = self._get_touch_resolution()
  File "D:\Python\lib\site-packages\poco\utils\airtest\input.py", line 51, in _get_touch_resolution
    return current_device().get_current_resolution()
  File "D:\Python\lib\site-packages\airtest\core\android\android.py", line 550, in get_current_resolution
    w, h = self.display_info["width"], self.display_info["height"]
  File "D:\Python\lib\site-packages\airtest\core\android\android.py", line 517, in display_info
    self._display_info = self.get_display_info()
  File "D:\Python\lib\site-packages\airtest\core\android\android.py", line 536, in get_display_info
    display_info = self.minicap.get_display_info()
  File "D:\Python\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\Python\lib\site-packages\airtest\core\android\minicap.py", line 136, in get_display_info
    display_info = json.loads(display_info)
  File "D:\Python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
用多开模拟器创建2个模拟器，连接第一个正常，连接第二个就会报错，关闭第一个，直接连第二个也不行，一直报这个错，能看出来是什么原因吗

**Comment by 742619648** [comment]
直接运行airtest写好的.py脚本，后缀改成.pyw，运行之后还是会不停的闪烁cmd窗口，这个要怎么解决

**Comment by rockywhisper** [comment]
@742619648  没有试过直接改为pyw运行，可以自己研究下哈。 

另外，这个issues在昨天的新包释放中已经修复，暂时先关闭了哈，后面有啥问题直接开新issue啦~  :-)
