### ISSUE TITLE
oppo R15机型无法查看页面元素（AirtestIDE_2018-10-11_py3_win64）

### ISSUE THREAD

**Issue by kfkvkkr** [AirtestProject/AirtestIDE#246]
复现步骤
连接OPPO手机（R15）
连接OPPO手机（手动安装AirtestIDE\airtest\core\android\static\apks下应用，并设置Yosemite输入法设为默认输入法）
观察左边UI渲染树无效果无法显示
预期效果
(左边UI渲染树显示UI元素)
AirtestIDE_2018-10-11_py3_win64
python 版本: python3
操作系统: Windows10 64bit
设备: OPPO
型号: [PADM00]
系统: [Android 8.1]
(别的信息)
Traceback (most recent call last):
File "airtest\core\android\adb.py", line 368, in shell
File "airtest\core\android\adb.py", line 326, in raw_shell
File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'']
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "app\plugins\poco\poco_probe.py", line 241, in initPoco
File "poco\drivers\android\uiautomation.py", line 146, in init
File "airtest\core\android\ime.py", line 109, in start
File "airtest\core\android\ime.py", line 77, in start
File "airtest\core\android\adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'']
initializing Android poco.
[10:26:33][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell dumpsys activity top
[10:26:33][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell dumpsys package com.netease.nie.yosemite
[10:26:33][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[10:26:33][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell settings get secure default_input_method
[10:26:34][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell ime list -a
[10:26:34][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell ime enable com.netease.nie.yosemite/.ime.ImeService
Traceback (most recent call last):
File "airtest\core\android\adb.py", line 368, in shell
File "airtest\core\android\adb.py", line 326, in raw_shell
File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'']
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "app\plugins\poco\poco_probe.py", line 241, in initPoco
File "poco\drivers\android\uiautomation.py", line 146, in init
File "airtest\core\android\ime.py", line 109, in start
File "airtest\core\android\ime.py", line 77, in start
File "airtest\core\android\adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'']
initializing Android poco.
[10:26:36][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell dumpsys activity top
[10:26:37][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell dumpsys package com.netease.nie.yosemite
[10:26:37][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[10:26:37][DEBUG]<airtest.core.android.adb> E:\迅雷下载\AirtestIDE_2018-10-11_py3_win64\AirtestIDE_2018-10-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 93d2aa4c shell settings get secure default_input_method

**Comment by rockywhisper** [comment]
@kfkvkkr 
你好，之前我们曾经处理过类似的报错，

`oppo`手机可以通过 `*#8011# `永久打开usb调试。
在部分新款手机系统中通过这个操作虽然能打开usb调试，并且`adb devices`能查看到序列号信息，但无法正常连接手机，在ide中跑脚本会出现类似你遇到的报错。
`

解决方法一：
 - 在`开发者选项`-`撤销usb调试授权`，然后关闭再打开usb调试，再次出现`一律允许使用这台计算机进行调试`弹窗，勾选后点击确定就能正常操作。

解决方法二：
 - 还原手机-抹掉全部内容和设置，重新进行配置。

**Comment by kfkvkkr** [comment]
撤销USB调试授权，依然不能显示UI渲染树 #
![image](https://user-images.githubusercontent.com/41918202/47126621-fbcc7d00-d2bb-11e8-8569-bd5afd0e0556.png)

**Comment by kfkvkkr** [comment]
还原也不行，只有老版本V0.0.18可以显示UI元素

**Comment by kfkvkkr** [comment]
还原手机无效，但是以前版本（v0.0.18连接是正常的）

**Comment by adolli** [comment]
@kfkvkkr 你有AndroidStudio吗？可能是oppo手机需要编译出正好是目标sdk版本的[PocoService.apk](https://github.com/AirtestProject/PocoService.apk)

**Comment by kfkvkkr** [comment]
具体要怎么编译
