### ISSUE TITLE
macos本地python命令行运行脚本ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by N-logan** [AirtestProject/AirtestIDE#307]
```py
from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco

poco = AndroidUiautomationPoco(
    use_airtest_input=True, screenshot_each_action=False)
start_app('com.x.x')
sleep(3)
add = poco('com.x.x:id/fg_main_addpickvideo_img')
add.click()
```
**python 版本:** `python3.7`
经过调试，发现出问题的代码在add.click(),完整错误如下：
```
Ran 1 test in 14.042s

OK
[02:31:39][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 4357c5db forward --remove tcp:15482
[02:31:39][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 4357c5db forward --remove tcp:11238
[02:31:39][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 4357c5db forward --remove tcp:15420
[02:31:39][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s 4357c5db forward --remove tcp:17661
[02:31:39][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception ignored in: <function RpcObjectProxy.__del__ at 0x125dc4ae8>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hrpc/object_proxy.py", line 114, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hrpc/client.py", line 63, in evaluate
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/hrpc/transport/http.py", line 23, in send
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py", line 112, in post
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/api.py", line 58, in request
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 503, in request
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 676, in merge_environment_settings
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/utils.py", line 760, in get_environ_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/utils.py", line 744, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2610, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2587, in proxy_bypass_macosx_sysconf
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2534, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by yimelia** [comment]
尝试在代码最后加一个sleep(1)试试？

**Comment by agoraHan** [comment]
sleep(1)仍会报错
Traceback (most recent call last):
  File "/Users/hanxing/Library/Python/3.6/lib/python/site-packages/hrpc/object_proxy.py", line 114, in __del__
  File "/Users/hanxing/Library/Python/3.6/lib/python/site-packages/hrpc/client.py", line 63, in evaluate
  File "/Users/hanxing/Library/Python/3.6/lib/python/site-packages/hrpc/transport/http.py", line 23, in send
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 112, in post
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 58, in request
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 499, in request
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 672, in merge_environment_settings
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/utils.py", line 692, in get_environ_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/utils.py", line 676, in should_bypass_proxies
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2612, in proxy_bypass
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 2589, in proxy_bypass_macosx_sysconf
