### ISSUE TITLE
打包成apk后运行shell报错

### ISSUE THREAD

**Issue by ningh2018** [AirtestProject/AirtestIDE#328]
用AirtestIDE 运行shell命令正常，但是打包成apk后运行报错

![image](https://user-images.githubusercontent.com/42169932/53147088-75190b00-35e1-11e9-9df2-a1e3b264ea00.png)

**复现步骤**
1. 连接小米note2 
2. AirtestIDE  编写脚本  shell("am broadcast -a com.tencent.tmgp.sgame.ExitTheGame")
3. 打包成apk
4. 运行  adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

**预期效果**
正确执行shell命令

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: Mi Note 2
 - 系统: miui 10.2

**Comment by ningh2018** [comment]
C:\Users\Administrator>adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

org.kivy.android.ExampleInstrumentedTest:
Error in launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 80, in test
  File "/data/data/com.netease.open.airbase/files/app/untitled1.air/untitled1.py", line 74, in <module>
    shell("am broadcast -a com.tencent.tmgp.sgame.ExitTheGame")
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 133, in shell
  File "copy_app/airtest\core\device.py", line 26, in shell
  File "copy_app/airtest\core\device.py", line 72, in _raise_not_implemented_error
NotImplementedError: Method not implemented on Kivy
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2160)


Time: 18.193
There was 1 failure:
1) launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest)
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 80, in test
  File "/data/data/com.netease.open.airbase/files/app/untitled1.air/untitled1.py", line 74, in <module>
    shell("am broadcast -a com.tencent.tmgp.sgame.ExitTheGame")
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 133, in shell
  File "copy_app/airtest\core\device.py", line 26, in shell
  File "copy_app/airtest\core\device.py", line 72, in _raise_not_implemented_error
NotImplementedError: Method not implemented on Kivy
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2160)

FAILURES!!!
Tests run: 1,  Failures: 1

**Comment by yimelia** [comment]
应该是不支持这样用的，`shell("xxx")`接口的意思是，执行 `adb shell xxxx` 指令，这个在电脑上运行的指令，放到apk里是不能跑的，因为apk里并没有“adb”这个东西。

**Comment by ningh2018** [comment]
好的，我是想通过shell发个广播，  那请问如何在apk里面执行shell命令呢， 或者如何让生成的apk跟自己的写的另外的一个app通讯？

**Comment by yimelia** [comment]
@ningh2018  要换个思路，shell是我们帮你封装好的运行 `adb shell xxx` ，而你在apk里就不是用adb来运行命令了，可以直接尝试一下直接运行你的命令行啊，去掉 adb shell就是你的命令行内容了，然后用Popen之类的方式直接运行命令试一下，我也没试过……

**Comment by jekiki** [comment]
# 测试程序在电脑上运行正常，在手机上有运行出错
+ ubuntu 18.04 
+ Android Debug Bridge version 1.0.40
+ Version 4986621
 
电脑环境 
+ win10 
+ ide v1.2.0
+ python37

代码片段
<pre>
from airtest.core.api import *
import logging
auto_setup(__file__)

logger = logging.getLogger("airtest")
logger.setLevel(logging.WARNING)

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco()

dev = `connect_device("android:///")`

def viewVideo():
    if checkstats(item="视频1") : print("viewVideo 完成");return
    checkAutoPlay()
    poco(text="视频学习").click()
    sleep()
    poco(text="联播频道").click()
    sleep()
    swipe((600,1400),(600,600))
    sleep()
    videocoms= poco("android.widget.ListView").children()
    
    print(len(videocoms))
    num=7 if 7<len(videocoms) else len(videocoms)

    for i in range(num):
        videocoms[i].click();
        sleep(10)
        keyevent("BACk")
        sleep()

</pre>

# ubuntu 错误提示

root@LAPTOP# adb shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

org.kivy.android.ExampleInstrumentedTest:
Error in launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 80, in test
  File "/data/data/com.netease.open.airbase/files/app/xyqg.air/xyqg.py", line 11, in <module>
    from poco.drivers.android.uiautomation import AndroidUiautomationPoco
  File "copy_app/poco\drivers\android\uiautomation.py", line 6, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\__init__.py", line 52, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\__init__.py", line 27, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\connectionpool.py", line 11, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\exceptions.py", line 2, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\packages\__init__.py", line 3, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\packages\ssl_match_hostname\__init__.py", line 16, in <module>
  File "/data/user/0/com.netease.open.airbase/files/app/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py", line 1
SyntaxError: Non-ASCII character '\xf3' in file /data/user/0/com.netease.open.airbase/files/app/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2084)


Time: 7.894
There was 1 failure:
1) launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest)
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 80, in test
  File "/data/data/com.netease.open.airbase/files/app/xyqg.air/xyqg.py", line 11, in <module>
    from poco.drivers.android.uiautomation import AndroidUiautomationPoco
  File "copy_app/poco\drivers\android\uiautomation.py", line 6, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\__init__.py", line 52, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\__init__.py", line 27, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\connectionpool.py", line 11, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\exceptions.py", line 2, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\packages\__init__.py", line 3, in <module>
  File "copy_app\lib\python2.7\site-packages\requests\packages\urllib3\packages\ssl_match_hostname\__init__.py", line 16, in <module>
  File "/data/user/0/com.netease.open.airbase/files/app/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py", line 1
SyntaxError: Non-ASCII character '\xf3' in file /data/user/0/com.netease.open.airbase/files/app/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2084)

FAILURES!!!
Tests run: 1,  Failures: 1

**Comment by yimelia** [comment]
在代码文件开头加上`# -*- coding: utf-8 -*-`

**Comment by jekiki** [comment]
[cid:59630E83-A4E6-4CEA-B17B-9274AE352AA8@mailmaster]
[cid:18C452C5-4836-492F-9E3B-9FAB896A29FA@mailmaster]
打包运行后依然出现相同的错误
[cid:ED597D39-E8EE-4F66-A1AD-7D034043C2E4@mailmaster]
<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=pchengzhwang&uid=pchengzhwang%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22pchengzhwang%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
pchengzhwang

pchengzhwang@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年3月26日 09:36，yimelia<notifications@github.com><mailto:notifications@github.com> 写道：

在代码文件开头加上# -*- coding: utf-8 -*-

**Comment by jekiki** [comment]
SyntaxError: Non-ASCII character '\xf3' in file /data/user/0/com.netease.open.airbase/files/app/lib/python2.7/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
报错文件_implementation.py，问题是否出现在程序内部，而不是代码编写的问题

**Comment by yimelia** [comment]
噢，是android poco的代码里报的错。
目前的apk打包功能暂时不支持android poco，但是我们已经找到了解决方案，但是还需要一点测试实践，会尽快放出更新的

**Comment by jekiki** [comment]
＋ 在电脑编写的时候是Python37，在Android中实现的时候是Python27，请问会不会存在3.x与2.x不兼容的问题。
＋ 请问有没有QQ群，微信群，微博等可以和更多的开发者一起交流技术。

**Comment by yimelia** [comment]
会，3.x和2.x之间的兼容性，建议先在电脑端用2.x测试过了之后再编apk
QQ群在官网首页有，但是现在满人了，还没有开二群，有问题建议直接github开帖子问
