### ISSUE TITLE
小米Mix2运行测试报错：airtest.core.error.AdbShellError: stdout[b''] stderr[b'']

### ISSUE THREAD

**Issue by Requiem4Eternity** [AirtestProject/AirtestIDE#355]
错误日志：

"D:\AirtestIDE_2019-01-15_py3_win64\AirtestIDE" runner "C:\Users\27150\Desktop\工作\AirTestScript\PecoVisitEveryPage.air"  --device Android://127.0.0.1:5037/462672a9 --log "C:\Users\27150\AppData\Local\Temp\AirtestIDE\scripts\870335a951f76f28c001b8a446ae4870"
============================================================

[Start running..]
save log in 'C:\Users\27150\AppData\Local\Temp\AirtestIDE\scripts\870335a951f76f28c001b8a446ae4870'
[02:57:40][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 wait-for-device
[02:57:40][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 shell getprop ro.build.version.sdk
[02:57:41][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 shell dumpsys activity top
[02:57:41][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 shell dumpsys package com.netease.nie.yosemite
[02:57:41][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[02:57:41][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 shell settings get secure default_input_method
[02:57:41][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 shell ime list -a
[02:57:42][DEBUG]<airtest.core.android.adb> D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 462672a9 shell ime enable com.netease.nie.yosemite/.ime.ImeService
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\core\android\adb.py", line 368, in shell
  File "airtest\core\android\adb.py", line 326, in raw_shell
  File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\27150\Desktop\工作\AirTestScript\PecoVisitEveryPage.air\PecoVisitEveryPage.py", line 9, in <module>
    poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
  File "D:\AirtestIDE_2019-01-15_py3_win64\poco\drivers\android\uiautomation.py", line 146, in __init__
    self.ime.start()
  File "airtest\core\android\ime.py", line 109, in start
  File "airtest\core\android\ime.py", line 77, in start
  File "airtest\core\android\adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'']

----------------------------------------------------------------------
Ran 1 test in 1.987s

FAILED (errors=1)
[Finished]

============================================================

**Comment by yimelia** [comment]
可以尝试设置yosemite输入法为默认输入法后重试

**Comment by Requiem4Eternity** [comment]
设置后依然发生报错，错误信息没有变化，
我发现PocoService没有被推送到设备安装，猜测可能是此原因导致。
其他正常运行的设备均被安装了这个APP

**Comment by yimelia** [comment]
手工安装一下试试呢？这个apk在IDE的安装包里有的 `poco\drivers\android\lib`

**Comment by Requiem4Eternity** [comment]
手工安装后依然出现相同的错误，是否还有什么需要安装的程序呢，
目前仅安装了PocoService,pocoservice.test,Yosemite以及RotationWatcher

**Comment by yimelia** [comment]
这个报错之前只有oppo和vivo系的手机才会出现，是因为启动yosemite输入法失败导致的，因此在输入法设置中将yosemite输入法设置为启用+默认输入法+当前输入法之后，一般就能正常运行了

**Comment by Requiem4Eternity** [comment]
嗯，确实是这个问题，设置为默认输入法后问题解决了一次，但运行完成后，系统输入法又被回复成了小米输入法。

**Comment by Requiem4Eternity** [comment]
相当于每次运行都必须更改一次默认输入法，比较麻烦。

**Comment by yimelia** [comment]
你是用wifi连接手机跑脚本的吗？

**Comment by Requiem4Eternity** [comment]
不是的，是直接USB连接的。
目前使用的Airtest IDE是最新的1.2.0了。

**Comment by yimelia** [comment]
IDE里是否设置了python.exe的路径？
我们这里也有小米MIX2这台机器，使用流畅，没有遇到你说的问题。。。

**Comment by yimelia** [comment]
我们使用的系统版本是MIUI10.2稳定版，输入法设置里也没有设置默认输入法的选项，只有当前输入法：
![image](https://user-images.githubusercontent.com/6896468/54343122-15aa9a00-4679-11e9-9503-de5c6a148cbe.png)

**Comment by Requiem4Eternity** [comment]
没事没事，我的问题。
我在连接后的输入法是搜狗小米版，然后在此情况下更改了默认输入法。
应该是你们在测试结束后对输入法做了还原操作，我这边才被还原成搜狗小米版输入法的。

**Comment by yimelia** [comment]
我们之前版本的airtest中，会判断usb连线状态如果发生了变更，就会自动还原到手机默认输入法。因此在wifi连接状态下，每运行一次脚本结束后都会重置输入法。这个问题在github上的最新airtest已经修复，但是IDE中还没有修复。
一般情况下，如果没有插拔过USB线应该不会出现这个问题才对。。

**Comment by OnTheWay111** [comment]
我最近在做机器人的业务，也发现这个问题了。我的是pip安装的1.1.6版本的airtest @yimelia
