### ISSUE TITLE
poco库找不到我的text("小程序")

### ISSUE THREAD

**Issue by jyl4944204** [AirtestProject/AirtestIDE#363]
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\jyl\pick_tuan\tuanDetail.air\tuanDetail.py", line 24, in <module>
    poco(text="小程序").click()
  File "C:\jyl\AirtestIDE_2019-01-15_py3_win64\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\jyl\AirtestIDE_2019-01-15_py3_win64\poco\proxy.py", line 285, in click
    ret = self.poco.click(pos_in_percentage)
  File "C:\jyl\AirtestIDE_2019-01-15_py3_win64\poco\pocofw.py", line 248, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "C:\jyl\AirtestIDE_2019-01-15_py3_win64\poco\utils\airtest\input.py", line 65, in click
    touch(pos, duration=self.default_touch_down_duration)
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 259, in touch
  File "airtest\core\android\android.py", line 337, in touch
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\utils\snippet.py", line 115, in wrapper
  File "airtest\core\android\minitouch.py", line 51, in install_and_setup
  File "airtest\core\android\minitouch.py", line 143, in setup_server
RuntimeError: minitouch setup timeout

**Comment by yimelia** [comment]
请问使用过的是什么型号的设备
