### ISSUE TITLE
paramiko这个库我单独运行python脚本是没问题的，在airtest调用这个脚本时，就会报ModuleNotFoundError: No module named 'paramiko'

### ISSUE THREAD

**Issue by jyl4944204** [AirtestProject/AirtestIDE#369]
paramiko这个库我单独运行python脚本是没问题的，在airtest调用这个脚本时，就会报ModuleNotFoundError: No module named 'paramiko'

**Comment by EraChen233** [comment]
可以把完整的报错信息截图贴出来吗？

**Comment by yimelia** [comment]
第三方库的调用请参考[文档](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python)

**Comment by jyl4944204** [comment]
installed version is 39, installer version is 39. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
[pocoservice.apk] background daemon started.
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\jyl\pick_tuan\orderStatus.air\orderStatus.py", line 12, in <module>
    from generateOrder import Order
  File "C:\jyl\pick_tuan\orderStatus.air\generateOrder.py", line 11, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

**Comment by jyl4944204** [comment]
> 可以把完整的报错信息截图贴出来吗？

installed version is 39, installer version is 39. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
[pocoservice.apk] background daemon started.
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\jyl\pick_tuan\orderStatus.air\orderStatus.py", line 12, in <module>
    from generateOrder import Order
  File "C:\jyl\pick_tuan\orderStatus.air\generateOrder.py", line 11, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

**Comment by yimelia** [comment]
要使用第三方库需要设置自己本地python路径，文档地址见上面那楼

**Comment by EraChen233** [comment]
AirtestIDE 运行时使用的python环境是AirtestIDE 内置的，你使用的paramiko是第三方库，内置的python环境不存在，所以可以在AirtestIDE上设置你自己的环境
在上面 @yimelia 提到的文档有说明

![image](https://user-images.githubusercontent.com/5961185/54809237-a9a1e480-4cbd-11e9-9f4a-649edb39581c.png)

http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python

![image](https://user-images.githubusercontent.com/5961185/54809299-d524cf00-4cbd-11e9-932b-fc33f52f2c2e.png)

**Comment by jyl4944204** [comment]
我设置了这个选项，但是在运行的时候我自己写的python脚本都导不进来啦
5037 -s 5ea7b025 wait-for-device
[04:19:48][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell getprop ro.build.version.sdk
custom setup
[04:19:48][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell dumpsys activity top
[04:19:48][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell dumpsys package com.netease.nie.yosemite
[04:19:49][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 288
[04:19:49][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell settings get secure default_input_method
[04:19:49][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell ime list -a
[04:19:50][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell dumpsys package com.netease.open.pocoservice
installed version is 41, installer version is 41. force_reinstall=False
[04:19:50][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[04:19:50][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 forward --no-rebind tcp:15353 tcp:10080
[04:19:50][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 forward --no-rebind tcp:19926 tcp:10081
[04:19:50][DEBUG]<airtest.core.android.adb> C:\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 5ea7b025 shell ps
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\python37\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "C:\python37\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\python37\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "C:\jyl\pick_tuan\orderStatus.air\orderStatus.py", line 11, in <module>
    from addTuan import Tuan
ModuleNotFoundError: No module named 'addTuan'

**Comment by yimelia** [comment]
@jyl4944204 
假如你自己写的python脚本中没有引用airtest的语句（就是说没有图片），那么在from import之前把脚本所在目录加进sys.path即可， `sys.path.append(r"xxxx")`
假如需要从一个.air中import另外一个.air里的函数，可以用`using`接口，参考[这里](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#air)

**Comment by jyl4944204** [comment]
> @jyl4944204
> 假如你自己写的python脚本中没有引用airtest的语句（就是说没有图片），那么在from import之前把脚本所在目录加进sys.path即可， `sys.path.append(r"xxxx")`
> 假如需要从一个.air中import另外一个.air里的函数，可以用`using`接口，参考[这里](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#air)

谢谢！

**Comment by jyl4944204** [comment]
> @jyl4944204
> 假如你自己写的python脚本中没有引用airtest的语句（就是说没有图片），那么在from import之前把脚本所在目录加进sys.path即可， `sys.path.append(r"xxxx")`
> 假如需要从一个.air中import另外一个.air里的函数，可以用`using`接口，参考[这里](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#air)

sys.path.append(r"generateOrder.py")
from generateOrder import Order
我是这样写的，但还是不行报错：
raceback (most recent call last):
  File "C:\python37\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "C:\python37\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\python37\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "C:\jyl\pick_tuan\orderStatus.air\orderStatus.py", line 14, in <module>
    from generateOrder import Order
ModuleNotFoundError: No module named 'generateOrder'

**Comment by jyl4944204** [comment]
> @jyl4944204
> 假如你自己写的python脚本中没有引用airtest的语句（就是说没有图片），那么在from import之前把脚本所在目录加进sys.path即可， `sys.path.append(r"xxxx")`
> 假如需要从一个.air中import另外一个.air里的函数，可以用`using`接口，参考[这里](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#air)

sys.path.append(r"generateOrder.py")
from generateOrder import Order
我是这样写的，但还是不行报错：
raceback (most recent call last):
File "C:\python37\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
six.reraise(*sys.exc_info())
File "C:\python37\lib\site-packages\six.py", line 693, in reraise
raise value
File "C:\python37\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
File "C:\jyl\pick_tuan\orderStatus.air\orderStatus.py", line 14, in 
from generateOrder import Order
ModuleNotFoundError: No module named 'generateOrder'

**Comment by yimelia** [comment]
sys.path.append(r"父路径")
而不是直接放一个.py在里面
