### ISSUE TITLE
命令行执行脚本遇到import不成功的问题

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/AirtestIDE#382]
**描述问题bug**
在AirtestIDE上运行某脚本非常顺利，但按照说明文档4.2节中的cmd命令行运行的时候却在from...import...语句中出错，提示没有找到模块，提示内容复制如下：

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\Users\user>"C:\AirtestIDE\AirtestIDE" runner "C:\AirtestIDE\workspace\wi
n7x64\KeyX_main.air"  --device Windows:/// --log "D:\Users\netca2019\AppData\Loc
al\Temp\AirtestIDE\scripts\c482d27dc1545698c6c84e5d1f5278b5"
save log in 'D:\Users\netca2019\AppData\Local\Temp\AirtestIDE\scripts\c482d27dc1
545698c6c84e5d1f5278b5'
[current_line] 2
[current_line] 23
[current_line] 24
[current_line] 25
[current_line] 27
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_install.air
[current_line] 28
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_open.air
[current_line] 29
[03:18:31][DEBUG]<airtest.core.api> using path: password_change.air
[current_line] 30
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_extend.air
[current_line] 31
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_PDFSigned.air
[current_line] 32
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_uninstall.air
[current_line] 33
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_setting.air
[current_line] 34
[03:18:31][DEBUG]<airtest.core.api> using path: KeyX_logging.air
[current_line] 36
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\AirtestIDE\workspace\win7x64\KeyX_main.air\KeyX_main.py", line 36, in
 <module>
    from KeyX_install import keyx_install

**ModuleNotFoundError: No module named 'KeyX_install'**

----------------------------------------------------------------------
Ran 1 test in 0.568s

FAILED (errors=1)

**复现步骤**
使用cmd命令行直接运行从AirtestIDE的log窗口中获得的命令行代码。

**Comment by EraChen233** [comment]
KeyX_install 是你自己写的模块？
方便把你执行脚本的命令截图出来吗？
还有 KeyX_install 相对于 KeyX_main 的路径
