### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\Administrator\\AppData\\Lo cal\\Temp\\AirtestIDE'

### ISSUE THREAD

**Issue by cnscj** [AirtestProject/AirtestIDE#398]
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\Administrator\\AppData\\Lo
cal\\Temp\\AirtestIDE'
login按skip之后就出现这个,一直打不开

**Comment by cnscj** [comment]
详细错误
queue size is: 10
Traceback (most recent call last):
  File "AirtestIDE.py", line 76, in <module>
  File "AirtestIDE.py", line 44, in main
  File "app\main_window.py", line 454, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 6
31, in exec_module
  File "app\plugins\airtest\plugin.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 6
31, in exec_module
  File "app\plugins\airtest\plugin_config.py", line 17, in <module>
  File "app\plugins\airtest\plugin_config.py", line 47, in AirtestConfig
  File "app\utils.py", line 164, in tmpPath
  File "os.py", line 210, in makedirs
  File "os.py", line 220, in makedirs
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\Administrator\\AppData\\Lo
cal\\Temp\\AirtestIDE'
[3028] Failed to execute script AirtestIDE
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-Break to quit

**Comment by yimelia** [comment]
尝试用管理员模式来打开看看？

**Comment by cnscj** [comment]
> 尝试用管理员模式来打开看看？

没有用,还是一样

**Comment by yimelia** [comment]
参考这个：https://zhidao.baidu.com/question/76060170.html?qbl=relate_question_0
设置一下你的本地的临时目录的权限 C:\Users\Administrator\AppData\Local\Temp\

**Comment by rockywhisper** [comment]
@cnscj 
你好，本issue暂时关闭了哈。
如有其它问题，随时提issue。
