### ISSUE TITLE
ios执行过程中出现崩溃会断开链接中断执行wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)

### ISSUE THREAD

**Issue by jeniva** [AirtestProject/AirtestIDE#404]
**描述问题bug**

ios的airtest ide执行过程中出现崩溃会断开链接中断执行,如果是脚本里面有加try-except进行保护，但是跑稳定性的时候还是很容易中断，有wda error 还有piple broken什么的，下面的是wda的错误日志。

**截屏**

the25times failed
[Manual Stopped]
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hongyangwei/Desktop/itcn\u5faa\u73af\u9884\u89c8.air/itcn\u5faa\u73af\u9884\u89c8.py", line 96, in <module>
    swipe(Template(r"tpl1548153988753.png", record_pos=(-0.291, 0.465), resolution=(750, 1334)), vector=[-0.0466, -0.2925])
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 301, in swipe
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/cv.py", line 42, in loop_find
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 203, in snapshot
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 44, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 37, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 110, in window_size
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 448, in window_size
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/Users/hongyangwei/Desktop/itcn\u5faa\u73af\u9884\u89c8.air/itcn\u5faa\u73af\u9884\u89c8.py", line 110, in <module>
    stop_app("com.ezviz.hikconnect")
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 158, in stop_app
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 267, in stop_app
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 256, in session
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 324, in __init__
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
wda.WDAError: WDAError(status=889, value=Application is not running, possibly crashed)
**复现步骤**

**预期效果**
跑稳定性的脚本能够持续跑1天不会断开，不会中断

**python 版本:** `python2.7`

**操作系统:** `Windows7 64bit`

**设备:**
 - 型号: iphone 7
 - 系统: [11.4.1
 - (别的信息) 

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by jeniva** [comment]
[12:30:37][DEBUG]<airtest.core.api> match result: {'result': (140, 477), 'rectangle': ((37, 432), (37, 523), (244, 523), (244, 432)), 'confidence': 0.9980133175849915}
[12:30:40][INFO]<airtest.core.api> Try finding:
Template(file:///Users/hongyangwei/Desktop/itcn循环预览.air/tpl1548154059704.png)
retry to connect, error: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
======================================================================
[Finished]
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/Users/hongyangwei/Desktop/itcn\u5faa\u73af\u9884\u89c8.air/itcn\u5faa\u73af\u9884\u89c8.py", line 120, in <module>
    touch(Template(r"tpl1548154059704.png", record_pos=(0.0, 0.028), resolution=(750, 1334)))
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 254, in touch
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/cv.py", line 42, in loop_find
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 159, in snapshot
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/ios/ios.py", line 143, in _neo_wda_screenshot
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 75, in httpdo
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/api.py", line 58, in request
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

----------------------------------------------------------------------
Ran 1 test in 1947.731s

FAILED (errors=1)
还有这样的错误，ios的链接不稳定，还是出现崩溃导致的？

**Comment by AndreRao** [comment]
我也出现这个情况，请问怎么解决？
我升级osx系统、xcode、Air test就一直出现这个问题

**Comment by EraChen233** [comment]
已知是iOS-Tagent稳定性问题，我们会尽快查证解决，烦请耐心等待更新

**Comment by raoqianghua** [comment]
> 已知是iOS-Tagent稳定性问题，我们会尽快查证解决，烦请耐心等待更新

请问下什么时候更新，等着用

**Comment by wenbinke** [comment]
同样遇到不稳定问题。

**Comment by NOBUGNOERRORHAHAHA** [comment]
同样遇到这样的问题，ios在做断网自动化，用hone健去手机设置处断网经常出现这样的问题

**Comment by 1111111Aa** [comment]
这个问题，请问解决了吗？ 我也一直有遇到

**Comment by jeniva** [comment]
目前连接不稳定的问题我是通过加try-except的方法，在except里面xcode build重新启动WDA进行解决的
