### ISSUE TITLE
无法识别设备

### ISSUE THREAD

**Issue by 9aither** [AirtestProject/AirtestIDE#41]
Traceback (most recent call last):
  File "app\plugins\device\device_panel\util.py", line 25, in adbDevices
  File "airtest\core\android\adb.py", line 189, in devices
  File "airtest\core\android\adb.py", line 165, in cmd
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 106-107: illegal multibyte sequence

**Comment by 9aither** [comment]
索尼XZ1 和 小米5

**Comment by adolli** [comment]
#29

**Comment by Meteorix** [comment]
@9aither 参考这个 https://github.com/AirtestProject/AirtestIDE/issues/29

**Comment by rockywhisper** [comment]
@9aither  最新版本已在软件内设置解决提示。
这个issue先关闭了哈。
