### ISSUE TITLE
window窗口上鼠标单击无反应

### ISSUE THREAD

**Issue by qinh2018** [AirtestProject/AirtestIDE#416]
问题分类：
* 测试开发环境AirtestIDE使用问题（本软件）

**描述问题bug**
使用了without embedding方式选定了window窗口后，图像识别可以定位到指定的位置上，但是鼠标单击无反应

**截屏**
抱歉，上传图片被屏蔽了

使用的是AirtestIDE_2019-04-16_py3_win64包，IDE版本是v1.2.1

**其他相关环境信息**
我选择的window窗口存在cocos.js，不知道和这个是不是有关系？

**Comment by yimelia** [comment]
1. 用了无嵌入方式来连接windows窗口的话，鼠标是可以正常操作窗口内容的， 请先确认鼠标可以点击窗口。
2. 如果是运行脚本时，能找到位置也执行了鼠标点击，但是实际无反应，请看一下是否有报错信息。如果有的话可以发上来。不过在这之前可以先尝试用管理员权限来启动IDE后重新尝试一遍。

**Comment by qinh2018** [comment]
1.已确认鼠标可以点击窗口
2.未选择管理员方式启动IDE时，可以识别图像，找到指定位置，但是无单击操作（已确认，在这个窗口里，可以手动单击鼠标，确认鼠标等无问题）；选择管理员方式启动IDE后，不能识别图像，无法找到指定位置。上述两个情况的操作一样，但结果一样

**Comment by yimelia** [comment]
找一下报错log发出来看看，在跟随IDE启动的另外那个黑色窗口里面

**Comment by yimelia** [comment]
有无使用管理员启动，对于脚本运行的图像识别应该没有影响的

**Comment by qinh2018** [comment]
[01:30:57][DEBUG]<airtest.aircv.template_matching> [Template] threshold=0.7, result={'result': (1085, 65), 'rectangle': ((1067, 51), (1067, 79), (1104, 79), (1104, 51)), 'confidence': 0.3104153573513031}
[01:30:57][DEBUG]<airtest.aircv.template_matching> find_best_result() run time is 0.04 s.
[01:30:57][DEBUG]<airtest.core.api> try match with BRISKMatching
[01:30:57][DEBUG]<airtest.core.api> 'Not enough feature points in input images !'
[01:30:57][DEBUG]<airtest.core.api> match result: None
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "D:\test.air\untitled.air\5_6.air\5_6.py", line 16, in <module>
    touch(Template(r"tpl1557129320167.png", record_pos=(-0.231, -0.155), resolution=(1366, 661)))
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 256, in touch
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 77, in loop_find
airtest.core.error.TargetNotFoundError: 'Picture Template(D:\\test.air\\untitled.air\\5_6.air\\tpl1557129320167.png) not found in screen'

----------------------------------------------------------------------
Ran 1 test in 21.006s

FAILED (errors=1)
[Finished]

**Comment by qinh2018** [comment]
### 跟随IDE启动的另外那个黑色窗口里面
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : ['C:\\Users\\qinhao\\AppData\\Local\\AirtestIDE\\AirtestIDE\\user.json']
[11:49:19][DEBUG]<airtest.core.android.adb> C:\Users\qinhao\Downloads\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
[MouseTrackingThread] start..
2296824 [0, 67, 1366, 728, 1] [1575772, 1641386, 4197040, 1705882]
[MouseTrackingThread] stop..

**Comment by yimelia** [comment]
匹配度低找不到的那个问题，运行完脚本后看一下报告里截图是不是正常的截图？

**Comment by qinh2018** [comment]
> 匹配度低找不到的那个问题，运行完脚本后看一下报告里截图是不是正常的截图？
匹配度低找不到运行完脚本后，报告里的截图不是正常的截图，我在https://github.com/AirtestProject/AirtestIDE/issues/416#issuecomment-489914634这个里边贴了一个图片，报告里的截图和这个图片是一样的

**Comment by yimelia** [comment]
是否用管理员模式启动，对于截图应该是没有影响的，只是部分机器上面不用管理员启动时，在点击的时候会因为权限不足导致报错，所以点击失败。
所以在使用管理员模式启动时，连接的窗口也是没有嵌入到IDE中的吗？能否截一个完整的图看一下具体一点的情况？
以及也可以考虑再试一下不选定窗口，直接连接桌面来运行脚本（点最右边这个按钮之后，把窗口完整地放在桌面上，然后点运行。如果是双屏，请尽量放在主屏幕上）：
![image](https://user-images.githubusercontent.com/6896468/57276076-0709bd80-70d3-11e9-8a3a-fbe34ac41adf.png)

**Comment by qinh2018** [comment]
> 是否用管理员模式启动，对于截图应该是没有影响的，只是部分机器上面不用管理员启动时，在点击的时候会因为权限不足导致报错，所以点击失败。
> 所以在使用管理员模式启动时，连接的窗口也是没有嵌入到IDE中的吗？能否截一个完整的图看一下具体一点的情况？
> 以及也可以考虑再试一下不选定窗口，直接连接桌面来运行脚本（点最右边这个按钮之后，把窗口完整地放在桌面上，然后点运行。如果是双屏，请尽量放在主屏幕上）：
> ![image](https://user-images.githubusercontent.com/6896468/57276076-0709bd80-70d3-11e9-8a3a-fbe34ac41adf.png)
1.在使用管理员模式启动时，连接的窗口也是没有嵌入到IDE中的，在设置里勾选了without embedding。
2.按照你说的，不选定窗口，直接连接桌面来运行脚本是可以的，能够解决问题。从运行后的报告看，截图也没有出现刚才说的黑屏
另外，请问选定窗口方式连接是什么原因导致截屏是黑屏的；除了选择直接连接桌面来运行外，还有更好的解决方法吗？

**Comment by yimelia** [comment]
可以提供一下你的操作系统版本、用来连接的软件是什么样的软件

我们接下来有对windows下截图准备进行迭代和测试，后面如果发了新版本可以再试用下，需要等待一段时间

**Comment by qinh2018** [comment]
1.使用Windows 10企业版，64位操作系统，版本：1809（OS 内部版本17763.437）
2.测试应用，是Windows系统桌面应用，应用内有动画，据了解使用了cocos.js，其他信息后续知道在补充
