### ISSUE TITLE
plugin load and device connection problem

### ISSUE THREAD

**Issue by bossturk** [AirtestProject/AirtestIDE#426]
I followed all the instructions but the problem is still the same

![ttttt](https://user-images.githubusercontent.com/39605293/57619949-01f3b500-7590-11e9-928c-70162b9870a1.png)

### Log

> Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : ['C:\\Users\\BossTurk\\AppData\\Local\\AirtestIDE\\AirtestIDE\\user.json']
[02:58:50][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 wait-for-device
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap ; echo ---$?---
[02:58:53][DEBUG]<airtest.core.android.minicap> install minicap
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.preview_sdk
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-22/x86/minicap.so /data/local/tmp/minicap.so
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[02:58:53][INFO]<airtest.core.android.minicap> minicap installation finished
[02:58:53][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[02:58:53][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 162, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 83, in __init__
  File "app\plugins\device\android\android_phone.py", line 111, in _initDev
  File "airtest\core\android\android.py", line 526, in display_info
    self._display_info = self.get_display_info()
  File "airtest\core\android\android.py", line 545, in get_display_info
    display_info = self.minicap.get_display_info()
  File "airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[02:58:54][DEBUG]<airtest.core.android.adb> C:\Users\BossTurk\Desktop\AirtestIDE_2019-04-16_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices

**Comment by yimelia** [comment]
if you're using emulator, check the `use javacap` and `use adb orientation`, and then click the `connect` button to connect the emulator.
![image](https://user-images.githubusercontent.com/6896468/57759594-cb9f6c80-772c-11e9-9849-fd82723e3fb4.png)
