### ISSUE TITLE
cocos-lua poco无法按照树状结构找到节点

### ISSUE THREAD

**Issue by ViolinTel** [AirtestProject/AirtestIDE#427]
**描述问题bug**
cocos-lua poco无法按照树状结构找到节点

**复现步骤**
1. 运行脚本

![0E677CE6-87C7-4EFD-AF69-22160060D3B5](https://user-images.githubusercontent.com/4182913/57681831-10f76780-7663-11e9-8409-31c0ea315591.png)

2. See error

![9F99EF33-8F29-46B2-864E-0D2C53ABD255](https://user-images.githubusercontent.com/4182913/57681840-16ed4880-7663-11e9-8c36-3cbe0375e60a.png)

**预期效果**
脚本正常运行，对应点击正常响应

**python 版本:** `python2.7`

**操作系统:** `Mac OS 10.14.4`

**设备:**
 - 型号: [HTC U11]
 - 系统: [Android 7.1.1]

**Comment by 13597977605** [comment]
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "C:\Users\cdtest\Desktop\untitled.air\untitled.air\untitled.py", line 11, in <module>
    poco("ball").swipe("up")
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 457, in swipe
    origin = self.get_position(focus)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\freezeui\hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\sdk\Selector.py", line 78, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\sdk\Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\freezeui\hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\utils\simplerpc\utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\utils\simplerpc\simplerpc.py", line 74, in wait
    self.agent.update()
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\utils\simplerpc\rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\utils\simplerpc\transport\tcp\main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "C:\installs\09_Others\Airtest\AirtestIDE_2019-05-09_py3_win64\poco\utils\simplerpc\transport\tcp\safetcp.py", line 39, in recv
    trunk = self.sock.recv(size)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
