### ISSUE TITLE
Airtest连接iOS真机crash

### ISSUE THREAD

**Issue by BugaoxingXXX** [AirtestProject/AirtestIDE#432]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题

**描述问题bug**
WebDriverAgent和iproxy配置好之后，启动airtest连接http://127.0.0.1:8100直接就crash退出

**复现步骤**
1. Xcode启动WebDriverAgent
2. 运行 iproxy 8100 8100
3. 启动Airtest，点击右下角的connect

**预期效果**
连接iOS机器成功

**python 版本:** `Python 3.7.3`

**操作系统:** `Mac mini 10.14`

**设备:**
 - 型号: [e.g. iPhone XS Max iOS 12.2]

**日志**
```
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : ['/Users/alonzo/Library/Application Support/AirtestIDE/AirtestIDE/user.json']
[10:02:05][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb devices
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/ios/ios_client.py", line 289, in run
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 82, in __init__
    self.rotation_watcher = RotationWatcher(self)
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/rotation.py", line 22, in __init__
    self.session = iosHandle.session
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 97, in session
    self.defaultSession = self.driver.session()
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 256, in session
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 324, in __init__
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
wda.WDAError: WDAError(status=13, value=+[XCAXClient_iOS sharedClient]: unrecognized selector sent to class 0x10132fe50

(
	0   CoreFoundation                      0x00000001aecef770 <redacted> + 256
	1   libobjc.A.dylib                     0x00000001adef7d00 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001aec0da60 <redacted> + 0
	3   CoreFoundation                      0x00000001aecf50fc <redacted> + 1412
	4   CoreFoundation                      0x00000001aecf6eb0 _CF_forwarding_prep_0 + 96
	5   WebDriverAgentLib                   0x0000000105a6c5d8 __37+[FBApplication fb_activeApplication]_block_invoke + 52
	6   WebDriverAgentLib                   0x0000000105a439b8 -[FBRunLoopSpinner spinUntilTrue:error:] + 152
	7   WebDriverAgentLib                   0x0000000105a438f8 -[FBRunLoopSpinner spinUntilTrue:] + 84
	8   WebDriverAgentLib                   0x0000000105a6c338 +[FBApplication fb_activeApplication] + 128
	9   WebDriverAgentLib                   0x0000000105a57d7c -[FBSession application] + 332
	10  WebDriverAgentLib                   0x0000000105a5eb4c +[FBSessionCommands currentCapabilities] + 124
	11  WebDriverAgentLib                   0x0000000105a5ea08 +[FBSessionCommands sessionInformation] + 288
	12  WebDriverAgentLib                   0x0000000105a5e118 +[FBSessionCommands handleGetActiveSession:] + 72
	13  WebDriverAgentLib                   0x0000000105a423d8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 220
	14  WebDriverAgentLib                   0x0000000105a4bf14 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 504
	15  RoutingHTTPServer                   0x0000000105afa3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	16  RoutingHTTPServer                   0x0000000105afab80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	17  libdispatch.dylib                   0x00000001ae7018f4 <redacted> + 20
	18  libdispatch.dylib                   0x00000001ae70e538 <redacted> + 96
	19  libdispatch.dylib                   0x00000001ae7018f4 <redacted> + 20
	20  libdispatch.dylib                   0x00000001ae70d794 _dispatch_main_queue_callback_4CF + 1012
	21  CoreFoundation                      0x00000001aec7f534 <redacted> + 16
	22  CoreFoundation                      0x00000001aec7a1e4 <redacted> + 1888
	23  CoreFoundation                      0x00000001aec79764 CFRunLoopRunSpecific + 452
	24  Foundation                          0x00000001af65957c <redacted> + 304
	25  WebDriverAgentLib                   0x0000000105a4af20 -[FBWebServer startServing] + 416
	26  WebDriverAgentRunner                0x0000000102677be8 -[UITestingUITests testRunner] + 124
	27  CoreFoundation                      0x00000001aecf7064 <redacted> + 148
	28  CoreFoundation                      0x00000001aebd3bc8 <redacted> + 324
	29  XCTest                              0x00000001012248e8 __24-[XCTestCase invokeTest]_block_invoke_2.202 + 72
	30  XCTest                              0x000000010128f388 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 76
	31  XCTest                              0x000000010122d1dc -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 116
	32  XCTest                              0x000000010122486c __24-[XCTestCase invokeTest]_block_invoke.196 + 212
	33  XCTest                              0x000000010127b9e4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 72
	34  XCTest                              0x000000010127b8f4 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 112
	35  XCTest                              0x0000000101224474 __24-[XCTestCase invokeTest]_block_invoke + 836
	36  XCTest                              0x0000000101281bec -[XCUITestContext performInScope:] + 152
	37  XCTest                              0x0000000101224044 -[XCTestCase testContextPerformInScope:] + 124
	38  XCTest                              0x000000010122411c -[XCTestCase invokeTest] + 156
	39  XCTest                              0x0000000101225c98 __26-[XCTestCase performTest:]_block_invoke_2 + 48
	40  XCTest                              0x000000010127b9e4 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 72
	41  XCTest                              0x000000010127b8f4 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 112
	42  XCTest                              0x0000000101225bac __26-[XCTestCase performTest:]_block_invoke.332 + 112
	43  XCTest                              0x000000010128c71c +[XCTContext runInContextForTestCase:block:] + 224
	44  XCTest                              0x0000000101225340 -[XCTestCase performTest:] + 684
	45  XCTest                              0x0000000101268474 -[XCTest runTest] + 64
	46  XCTest                              0x000000010121ff68 __27-[XCTestSuite performTest:]_block_invoke + 284
	47  XCTest                              0x000000010121f864 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 76
	48  XCTest                              0x000000010121fb14 -[XCTestSuite performTest:] + 292
	49  XCTest                              0x0000000101268474 -[XCTest runTest] + 64
	50  XCTest                              0x000000010121ff68 __27-[XCTestSuite performTest:]_block_invoke + 284
	51  XCTest                              0x000000010121f864 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 76
	52  XCTest                              0x000000010121fb14 -[XCTestSuite performTest:] + 292
	53  XCTest                              0x0000000101268474 -[XCTest runTest] + 64
	54  XCTest                              0x000000010121ff68 __27-[XCTestSuite performTest:]_block_invoke + 284
	55  XCTest                              0x000000010121f864 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 76
	56  XCTest                              0x000000010121fb14 -[XCTestSuite performTest:] + 292
	57  XCTest                              0x0000000101268474 -[XCTest runTest] + 64
	58  XCTest                              0x0000000101299ff8 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 180
	59  XCTest                              0x000000010129a0d4 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 68
	60  XCTest                              0x0000000101237760 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 524
	61  XCTest                              0x0000000101299da4 -[XCTTestRunSession runTestsAndReturnError:] + 624
	62  XCTest                              0x0000000101204488 -[XCTestDriver runTestsAndReturnError:] + 452
	63  XCTest                              0x0000000101288a2c _XCTestMain + 2252
	64  WebDriverAgentRunner-Runner         0x0000000100e9bb60 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	65  WebDriverAgentRunner-Runner         0x0000000100e9ba68 _XCTRunnerRunTests + 0
	66  CoreFoundation                      0x00000001aec7f78c <redacted> + 28
	67  CoreFoundation                      0x00000001aec7f074 <redacted> + 276
	68  CoreFoundation                      0x00000001aec79e74 <redacted> + 1008
	69  CoreFoundation                      0x00000001aec79764 CFRunLoopRunSpecific + 452
	70  GraphicsServices                    0x00000001b0eb5dd4 GSEventRunModal + 108
	71  UIKitCore                           0x00000001dbbd000c UIApplicationMain + 216
	72  WebDriverAgentRunner-Runner         0x0000000100e9bd3c main + 192
	73  libdyld.dylib                       0x00000001ae738ffc <redacted> + 4
))
QThread: Destroyed while thread is still running
Received signal 6
 [0x000118e89de6]
 [0x7fff61d96b5d]
 [0x7fff61d5cf96]
 [0x7fff61c566a6]
 [0x000115acf079]
 [0x000115ad085f]
 [0x000115adbb4c]
 [0x000110f4a6dc]
 [0x0001111df665]
 [0x0001111df40a]
 [0x000108a74569]
 [0x000108a53bd5]
 [0x000108a5918c]
 [0x000108a65c1d]
 [0x000108a6541f]
 [0x000108ade158]
 [0x000108ae609d]
 [0x000108ae4e01]
 [0x000108ae1597]
 [0x000108ae588f]
 [0x000108ae645b]
 [0x000108a193e7]
 [0x000108a19505]
 [0x000108a19220]
 [0x00011104d9b8]
 [0x00011104d8b7]
 [0x00011104e418]
 [0x00011104e38a]
 [0x000115cbf964]
 [0x0001165c9f12]
 [0x0001165cb2ed]
 [0x00011619950a]
 [0x000115c9654f]
 [0x000115c97722]
 [0x00011e96f3de]
 [0x00011e96fc91]
 [0x7fff357555e3]
 [0x7fff35755589]
 [0x7fff35738f3b]
 [0x7fff35738505]
 [0x7fff35737e0e]
 [0x7fff34a249db]
 [0x7fff34a24715]
 [0x7fff34a244a6]
 [0x7fff32dbeffb]
 [0x7fff32dbdd93]
 [0x7fff32db7eb0]
 [0x00011e96ea8d]
 [0x000115c920a2]
 [0x000115c96c62]
 [0x0001162886f2]
 [0x000108a6229b]
 [0x000108ae4e27]
 [0x000108ae1597]
 [0x000108ae609d]
 [0x000108ae4e01]
 [0x000108ae1597]
 [0x000108ae609d]
 [0x000108ae4e01]
 [0x000108ae1597]
 [0x000108ae588f]
 [0x000108ada954]
[end of stack trace]
Abort trap: 6
```

**Comment by sunhao0313** [comment]
Hi,您好，我也遇到了这个问题，请问您解决了吗？多谢赐教~

**Comment by sunhao0313** [comment]
@BugaoxingXXX Hi,您好，我也遇到了这个问题，请问您解决了吗？多谢赐教~

**Comment by sunhao0313** [comment]
@EraChen233 Hi，Chen，昨天咱们加过qq私聊的，就是这个问题哈
