### ISSUE TITLE
airtest闪退问题

### ISSUE THREAD

**Issue by Nordrassil01** [AirtestProject/AirtestIDE#46]
在使用poco框架录制脚本结合airtest截图功能，在跑完一遍脚本流程后，再尝试截图时airtest出现闪退

**Comment by rockywhisper** [comment]
你好，请问是否方便提供对应的IDE控制台报错截图。

**Comment by Nordrassil01** [comment]
只有此图

**Comment by Nordrassil01** [comment]
Traceback (most recent call last):
  File "app\plugins\airtest\plugin.py", line 212, in touchUp
  File "app\plugins\airtest\airtest_recorder.py", line 345, in mouseUp
  File "app\plugins\airtest\airtest_assistant.py", line 84, in _getTargetImage
  File "airtest\aircv\aircv.py", line 80, in crop_image
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by rockywhisper** [comment]
@Nordrassil01   Hi，上周的版本中已修正此处的崩溃问题。
可以在官网上下载新的IDE即可，**版本: 0.0.9 (2018-03-27)**。
