### ISSUE TITLE
AirtestIDE无法连接到小米Mix 2s

### ISSUE THREAD

**Issue by wang1103xin** [AirtestProject/AirtestIDE#463]
**问题分类**
* 测试开发环境AirtestIDE使用问题

**描述问题bug**
AirtestIDE无法连接到小米Mix 2s

**复现步骤**
1. 通过数据线连接小米Mix 2s到电脑
2. 点击AirtestIDE上的“refresh ADB”按钮，确认连接的手机出现在设备列表中
3. 点击设备右侧的“connect”按钮

**预期效果**
成功连接到手机，Devices窗口与手机页面同步

**结果**
AirtestIDE报错，无法连接到手机
操作日志如下：
```
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 wait-for-device
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell getprop ro.build.version.sdk
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell ls /data/local/tmp/minicap
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell ls /data/local/tmp/minicap.so
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
version:5
skip install minicap
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell pm path jp.co.cyberagent.stf.rotationwatcher
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-bIx9OLvh2kMmiTGWSuwGoA==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 forward --no-rebind tcp:16583 localabstract:minicap_16583
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 3d757927 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
Failed to execute ADB commands, please read [Docs](http://airtest.netease.com/docs/en/3_faq/android_connection.html)

```

**python 版本:** `python3.6`

**操作系统:** `macOS 10.14.5`

**设备:**
 - 型号: [小米Mix 2s]
 - 系统: [Android 9]
 - MIUI 版本: [MIUI 10 9.7.4开发版]

**其他相关环境信息**
(在Windows 10 上同样遇到此问题。)

**Comment by yimelia** [comment]
小米手机有一些选项需要打开，请问是否每个都打开了？
http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#id8

**Comment by wang1103xin** [comment]
我在这个手机上使用Airtest已经有一段时间了的，从昨天开始才出现这个问题的，至于你给的FAQ里列出的需要打开的选项，我都是已经打开了的。

![WechatIMG958](https://user-images.githubusercontent.com/15829256/60808069-04524400-a1ba-11e9-8dc1-52e7c08f8229.jpeg)

**Comment by wang1103xin** [comment]
昨天手机系统升级了一下，不知道是否会有关联呢？
![WechatIMG959](https://user-images.githubusercontent.com/15829256/60809465-49c44080-a1bd-11e9-8d0e-782b5080b4fd.jpeg)

**Comment by yimelia** [comment]
在mac下先用命令行来启动IDE，类似这样：
```
$ cd /Applications/AirtestIDE.app/Contents/MacOS
$ ./AirtestIDE
```
然后在连接手机时，出错的时候看看这个命令行里打出来的报错内容是什么，贴上来看看。

以及，升级到新版本的MIUI后，看一下这个选项有没有选上：
>除了上述开发者选项中需要注意开启 允许通过USB安装应用 之外，还可以查看手机设置—》授权管理—》USB安装管理—》去掉USB安装应用的相关限制。

**Comment by wang1103xin** [comment]
谢谢回复！首先是升级后的手机的“USB安装管理”，如下图所示，什么也没有，所以应该是没有什么限制的。
![Android_授权管理页面_20190709 (1)](https://user-images.githubusercontent.com/15829256/60864337-e33f3100-a255-11e9-89bc-a68df7814ba8.png)

从终端启动后，复现问题的完整日志如下：
[命令行启动后复现错误时的日志190709.log](https://github.com/AirtestProject/AirtestIDE/files/3371479/190709.log)
报错内容：
```
[02:22:49][ERROR]<airtest> Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/util.py", line 480, in run
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/util.py", line 471, in _get_android_frame
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minicap.py", line 24, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minicap.py", line 325, in get_frame_from_stream
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/snippet.py", line 106, in ready_func
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minicap.py", line 219, in get_stream
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minicap.py", line 233, in _get_stream
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minicap.py", line 298, in _setup_stream_server
RuntimeError: minicap server setup timeout
```

**Comment by yimelia** [comment]
看一下这个新版本系统里，android版本是多少？

**Comment by wang1103xin** [comment]
这次的更新只是一个小更新，所以Android版本并没有改变，还是 Android 9 
![WechatIMG960](https://user-images.githubusercontent.com/15829256/60879221-ce719600-a273-11e9-9b75-2c90eb656afc.jpeg)

**Comment by yimelia** [comment]
如果是已root的手机，可能会因为本地文件夹权限已被修改，导致Airtest没有权限将相关文件放入手机内，可以先检查手机内的 /data/local/tmp 文件夹是否有写入权限
如果手机曾经安装过 STF 库，可能会出现不能正常点击屏幕等问题，可以尝试清空原先安装的STF相关文件（执行指令 adb shell rm /data/local/tmp/mini* ）后，再重新将手机连接到IDE中进行初始化

**Comment by wang1103xin** [comment]
> 如果是已root的手机，可能会因为本地文件夹权限已被修改，导致Airtest没有权限将相关文件放入手机内，可以先检查手机内的 /data/local/tmp 文件夹是否有写入权限

我的手机没有root过。

> 尝试清空原先安装的STF相关文件（执行指令 adb shell rm /data/local/tmp/mini* ）后，再重新将手机连接到IDE中进行初始化

很遗憾，清空stf相关文件后，重新连接到IDE，还是遇到了一样的问题。在报错后，进入了手机的”/data/local/tmp“目录，看到stf相关的文件已经重新生成了，所以该文件夹的写入权限应该是没有问题的吧

**Comment by wang1103xin** [comment]
补充一个情况哦：如果脚本只是使用了poco，而没有涉及到图像识别的话，脚本仍然是可以正常运行的；如果脚本里使用了涉及到图像识别的wait，touch等方法的话，脚本执行时就会报以下错误：
```
Traceback (most recent call last):
  File "/Users/mzl/PycharmProjects/DailyTask/dailytask/app_entry.py", line 282, in <module>
    'qqac': check_qqac(),
  File "/Users/mzl/PycharmProjects/DailyTask/dailytask/app_entry.py", line 182, in check_qqac
    if exists(Template(resource_file + 'tpl1553261848451.png', record_pos=(0.437, 0.654), resolution=(1080, 2160))):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/api.py", line 408, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/android.py", line 216, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 325, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 219, in get_stream
    stopped = next(gen)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 233, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 298, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout
```
完整日志请见：
[执行脚本出错日志190709.log](https://github.com/AirtestProject/AirtestIDE/files/3373091/190709.log)

**Comment by yimelia** [comment]
可以先在connect的时候勾选`use javacap`，用这个模式来连接手机会避开minicap，如果在使用中有遇到报错，可能需要把第二个选项`use adb orientation`也勾选上之后再connect。
我们这里暂时没有这个MIUI版本的手机，需要一些时间再看看是什么问题

**Comment by wang1103xin** [comment]
> 可以先在connect的时候勾选 `use javacap`，用这个模式来连接手机会避开minicap

谢谢，这样操作后IDE确实可以正常连接到手机了！
请问代码执行的时候是否也可以指定  `use javacap` 呢？

**Comment by yimelia** [comment]
是的，需要指定use javacap
至于为什么最新版本MIUI用不了，我们再看看

**Comment by rfirefly** [comment]
我也是这个问题，windows + mix2s
选择use javacap终于解决了👍

**Comment by naodeng** [comment]
选择use javacap 效果太差了，操作卡的像幻灯片一样。
 小米mix2  MIUI10 9.8.22|开发版 安卓版本是9.0
看报错提示是minica启动报错了，通过查阅minicap官方文档，是支持android9.0的，不知道导致问题的原因具体是啥

**Comment by ghost** [comment]
> 可以先在connect的时候勾选`use javacap`，用这个模式来连接手机会避开minicap，如果在使用中有遇到报错，可能需要把第二个选项`use adb orientation`也勾选上之后再connect。
> 我们这里暂时没有这个MIUI版本的手机，需要一些时间再看看是什么问题

同样的问题，不过都开启了也还是报minicap server setup timeout
