### ISSUE TITLE
AirtestIDE中链接ios设备后闪退

### ISSUE THREAD

**Issue by freeskyday** [AirtestProject/AirtestIDE#503]
在AirtestIDE中输入ios设备地址后，点击connet后，AirtestIDE闪退。
AirtestIDE版本：mac 1.2.1
手机设备型号：iphone7
手机系统：12.2
python:2.7.10

后台窗口报错:
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : ['/Users/xuewei/Library/Application Support/AirtestIDE/AirtestIDE/user.json']
[04:07:02][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb devices
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/ios/ios_client.py", line 289, in run
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 82, in __init__
    self.rotation_watcher = RotationWatcher(self)
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/rotation.py", line 22, in __init__
    self.session = iosHandle.session
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 97, in session
    self.defaultSession = self.driver.session()
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 252, in session
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 191, in status
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 77, in httpdo
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/requests/models.py", line 799, in json
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
QThread: Destroyed while thread is still running
Received signal 6
 [0x000122680de6]
 [0x7fff63c00b5d]
 [0x00010fcab000]
 [0x7fff63aba6a6]
 [0x000114d36079]
 [0x000114d3785f]
 [0x000114d42b4c]
 [0x000114a8e6dc]
 [0x0001152c3665]
 [0x0001152c340a]
 [0x000112052569]
 [0x000112031bd5]
 [0x00011203718c]
 [0x000112043c1d]
 [0x00011204341f]
 [0x0001120bc158]
 [0x0001120c409d]
 [0x0001120c2e01]
 [0x0001120bf597]
 [0x0001120c388f]
 [0x0001120c445b]
 [0x000111ff73e7]
 [0x000111ff7505]
 [0x000111ff7220]
 [0x000114b919b8]
 [0x000114b918b7]
 [0x000114b92418]
 [0x000114b9238a]
 [0x000114f26964]
 [0x0001200ebf12]
 [0x0001200ed2ed]
 [0x0001155a250a]
 [0x000114efd54f]
 [0x000114efe722]
 [0x0001280f03de]
 [0x0001280f0c91]
 [0x7fff37adc683]
 [0x7fff37adc629]
 [0x7fff37abffeb]
 [0x7fff37abf5b5]
 [0x7fff37abeebe]
 [0x7fff36d1e1ab]
 [0x7fff36d1dee5]
 [0x7fff36d1dc76]
 [0x7fff350b679d]
 [0x7fff350b548b]
 [0x7fff350af5a8]
 [0x0001280efa8d]
 [0x000114ef90a2]
 [0x000114efdc62]
 [0x0001156916f2]
 [0x00011204029b]
 [0x0001120c2e27]
 [0x0001120bf597]
 [0x0001120c409d]
 [0x0001120c2e01]
 [0x0001120bf597]
 [0x0001120c409d]
 [0x0001120c2e01]
 [0x0001120bf597]
 [0x0001120c388f]
 [0x0001120b8954]
[end of stack trace]
Abort trap: 6

**Comment by EraChen233** [comment]
xcode 的log 窗口输出什么？

**Comment by freeskyday** [comment]
> xcode 的log 窗口输出什么？

你好，我的xcode和ios真机是部署在另外一台电脑（执行机器）的。我用的本地机器输入ip和端口连接的。我看了执行机器上xcode的log，没有输出。 @EraChen233

**Comment by EraChen233** [comment]
在浏览器打开inspector页面，看一下能否看到截图。
http://127.0.0.1:8100/inspector 
（把ip换成你链接用的ip）

**Comment by freeskyday** [comment]
> 在浏览器打开inspector页面，看一下能否看到截图。
> http://127.0.0.1:8100/inspector
> （把ip换成你链接用的ip）

你好，我在我的电脑上访问了这个链接（已换ip），提示发送的响应无效。我在执行机器上访问，可以看到截图。因为我的同事他的本地机器可以正常连接（不会像我本地一样，点击connect就崩溃，他的是可以正常使用的），我也让他访问了这个链接，但他的提示和我的却是一样，提示发送的响应无效。

**Comment by EraChen233** [comment]
检查一下网络，是否必须内网连接或者其他网络因素，iOS连接的原理是在Mac上开一个服务，IDE通过http请求和它进行交互。在浏览器打开开发者模式看一下网络请求，是否404.

**Comment by freeskyday** [comment]
> 检查一下网络，是否必须内网连接或者其他网络因素，iOS连接的原理是在Mac上开一个服务，IDE通过http请求和它进行交互。在浏览器打开开发者模式看一下网络请求，是否404.

你好，不好意思之前忘记告诉你网络情况。我在出现这个问题的时候，第一时间检查了网络（因为我们办公室有好几个路由器，分属于不同的内网）。我的本地机器和执行机器是属于同一网络内，并且我测试过，这两者之间的网络请求是畅通的。
