### ISSUE TITLE
[Start running..] [24675] Failed to execute script AirtestIDE,启动不了

### ISSUE THREAD

**Issue by chrisyekui** [AirtestProject/AirtestIDE#517]
[Start running..]
[24675] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/AirtestIDE.py", line 79, in <module>
  File "/Users/wjjn3033/dev/idestable/airtest-ide/AirtestIDE.py", line 57, in main
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/widgets/code_runner/tracer.py", line 72, in run_pyfile
  File "/Users/yekui/workspace/untitled.py", line 8, in <module>
    start_app('com.XXXXX.XXXXXX')
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 148, in start_app
AttributeError: 'NoneType' object has no attribute 'start_app'
[Finished]

**Comment by EraChen233** [comment]
请检查一下IDE是否已连接一台手机
