### ISSUE TITLE
AndroidUiautomationPoco参数force_restart为false时候第二次运行报错

### ISSUE THREAD

**Issue by geonsme** [AirtestProject/AirtestIDE#54]
使用python -m airtest run启动，如果force_restart为false，第二次启动会报错，报错如下
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\airtest\cli\runner.py", line 92, in runTest
    exec(compile(code, pyfilepath.encode(sys.getfilesystemencoding()), 'exec')) in self.scope
  File "C:\Users\hzluohuili\Desktop\airtest_testcase\test.air\test.py", line 25, in <module>
    mail_login_btn = items[2].child("android.widget.RelativeLayout").child("com.netease.pm01:id/netease_mpay__login_channel_icon")
  File "D:\Python27\lib\site-packages\poco\proxy.py", line 182, in __getitem__
    nodes = self._do_query(multiple=True, refresh=True)
  File "D:\Python27\lib\site-packages\poco\proxy.py", line 653, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "D:\Python27\lib\site-packages\poco\utils\hrpc\hierarchy.py", line 27, in select
    return self.selector.select(query, multiple)
  File "D:\Python27\lib\site-packages\hrpc\object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "D:\Python27\lib\site-packages\hrpc\client.py", line 78, in evaluate
    raise RpcRemoteException(resp)
RpcRemoteException: java.lang.reflect.InvocationTargetException:

|--   Remote Traceback   --|

java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:169)
        at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
        at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: UiAutomation not connected!
        at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
        at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:414)
        at com.netease.open.pocoservice.Dumper.getRoot(Dumper.java:30)
        at com.netease.open.pocoservice.Dumper.getRoot(Dumper.java:17)
        at com.netease.open.libpoco.sdk.Selector.getRoot(Selector.java:123)
        at com.netease.open.libpoco.sdk.Selector.select(Selector.java:37)
        ... 6 more

|--   Remote Traceback end   --|

----------------------------------------------------------------------
Ran 1 test in 2.002s

FAILED (errors=1)
exiting.......

**Comment by Meteorix** [comment]
你好，目前poco-android的server稍有问题。force_restart=False是为了在AirtestIDE中不印象Hierarchy的获取，但是命令行运行时不存在这个问题，所以建议命令行运行时先去掉这个参数。

当然，我们会尽量修复这个bug

**Comment by adolli** [comment]
Fixed. please update `poco` by the following command or use the lastest AirtestIDE.
```
pip install -U pocoui
```
