### ISSUE TITLE
启动脚本报错

### ISSUE THREAD

**Issue by zhengjun110** [AirtestProject/AirtestIDE#543]
直接录制脚本开始播放提示如下错误

[Start running..]
[7260] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 49, in main
  File "app\widgets\code_runner\ide_launcher.py", line 70, in run_main
  File "airtest\cli\runner.py", line 137, in run_script
  File "app\widgets\code_runner\ide_launcher.py", line 32, in __init__
  File "app\widgets\code_runner\ide_launcher.py", line 39, in _getLoggerLevelByPyQt
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[Finished]

**Comment by yimelia** [comment]
抱歉，这个是新版本的一个BUG，我们已经修复了这个问题并且重新更新包文件了，可以重新下载一次AirtestIDE的包
