### ISSUE TITLE
AttributeError: 'PocoWindow' object has no attribute 'phone_offsetx'

### ISSUE THREAD

**Issue by KonStg** [AirtestProject/AirtestIDE#551]
**Describe the bug**
When selecting an item in Poco Assistant, an error appears in the console. The rectangle of the selected object is not displayed.
```
Traceback (most recent call last):
  File "app\plugins\poco\poco_window.py", line 391, in clickUi
  File "app\plugins\poco\poco_window.py", line 490, in showRubberBandInWindows
  File "app\plugins\poco\poco_window.py", line 439, in _getRubberbandGeomentry
AttributeError: 'PocoWindow' object has no attribute 'phone_offsetx'
```

**Screenshots**

![image](https://user-images.githubusercontent.com/6781403/64980406-72a23980-d8c2-11e9-9dca-7c97fc4518d3.png)

![Annotation 2019-09-16 203950](https://user-images.githubusercontent.com/6781403/64980285-340c7f00-d8c2-11e9-8765-98f6da09c732.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to Poco - integrated Windows app (Devices > Windows App Connection > Search Window)
2. Select Poco Assistant > Std-broker
3. Select any available node below

**Expected behaviour**
Selected node rect should be drawn on the screen.

**AirtestIDE version:** `1.2.2`
**Platform:** `Windows10 64bit 1903`

**Additional context**
Poco hierarchy viewer works great with same input data.

![Annotation 2019-09-16 203549](https://user-images.githubusercontent.com/6781403/64980283-340c7f00-d8c2-11e9-8173-1adc521708b0.png)

**Comment by EraChen233** [comment]
update poco to version 1.0.78

**Comment by KonStg** [comment]
@EraChen233 
Still not fixed with Poco 1.0.79 
I copied this folder `https://github.com/AirtestProject/Poco/tree/master/poco` into airtest main dir (where AirtestIDE.exe is located). And the problem persists.

**Comment by EraChen233** [comment]
My mistake... 
Poco in AirtestIDE cannot be manually updated.
So you can download an old version of the IDE (eg: 1.2.1) or wait for the new version to be released.
