### ISSUE TITLE
使用了POCO后，控件一会抓得到一会抓不到

### ISSUE THREAD

**Issue by yuanzhengjie** [AirtestProject/AirtestIDE#58]
树一会有一会没有，同样的控件有时能够click有时无法click。APK和脚本都没有变过，这是什么原因？

**Comment by adolli** [comment]
能贴一下你的完整脚本和界面截图吗？顺便还有click不上时的报错信息

**Comment by yuanzhengjie** [comment]
![2018-04-04_184247](https://user-images.githubusercontent.com/36287208/38303286-31103570-3838-11e8-9430-bfc250565597.png)
![2018-04-04_184019](https://user-images.githubusercontent.com/36287208/38303287-3148fe1e-3838-11e8-9715-6d76fc5bd62b.png)
![2018-04-04_183951](https://user-images.githubusercontent.com/36287208/38303288-317f94e2-3838-11e8-991c-06912608dda8.png)
![2018-04-04_183916](https://user-images.githubusercontent.com/36287208/38303289-31b632ae-3838-11e8-9a39-3edcd43eb036.png)

**Comment by TreHack** [comment]
@yuanzhengjie 运行的时候暂时先把ide的poco辅助窗那里选择stop。这个bug我们修复一下

**Comment by yuanzhengjie** [comment]
@TreHack 
![2018-04-04_190011](https://user-images.githubusercontent.com/36287208/38304043-87d1c232-383a-11e8-957c-15d768af23bd.png)
![2018-04-04_190024](https://user-images.githubusercontent.com/36287208/38304051-8eaf9fac-383a-11e8-8860-0b22b6e5214f.png)
这个是什么错？

**Comment by TreHack** [comment]
@yuanzhengjie 等游戏启动后才能初始化UnityPoco(), 因为游戏启动后server才启动。你可以在初始化poco之前写个wait语句等待游戏的某个画面出现。

**Comment by yuanzhengjie** [comment]
@TreHack 我游戏其实是启动着的

**Comment by yuanzhengjie** [comment]
@TreHack 顺便说一句，我把ide的POCO辅助停了后也会有无法定位的情况
提示错误如下
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 84, in runTest
  File "D:\airtest\test_air.air\test_air.py", line 15, in <module>
    poco('btn_joystick').swipe('up', duration=2)
  File "poco\proxy.py", line 21, in wrapped
  File "poco\proxy.py", line 340, in swipe
  File "poco\proxy.py", line 404, in get_position
  File "poco\proxy.py", line 37, in wrapped
  File "poco\proxy.py", line 524, in attr
  File "poco\proxy.py", line 653, in _do_query
  File "poco\freezeui\hierarchy.py", line 89, in select
  File "poco\sdk\Selector.py", line 77, in select
  File "poco\sdk\Selector.py", line 70, in getRoot
  File "poco\freezeui\hierarchy.py", line 35, in getRoot
  File "poco\utils\simplerpc\utils.py", line 13, in new_func
  File "poco\utils\simplerpc\simplerpc.py", line 75, in wait
RuntimeError: <poco.utils.simplerpc.simplerpc.Callback object at 0x0000000003130DA0> timeout error

**Comment by TreHack** [comment]
@yuanzhengjie 这个我们先看看哈

**Comment by yuanzhengjie** [comment]
@TreHack 做了个给测试用的工具。。。肯定会被测出暴多的问题。。。偷笑

**Comment by TreHack** [comment]
@yuanzhengjie timeout error 的问题已经修复，更新unity sdk即可。欢迎使用。
