### ISSUE TITLE
在centos 使用python命令行运行脚本，用图片识别功能时执行报错

### ISSUE THREAD

**Issue by 93631830** [AirtestProject/AirtestIDE#580]
(venv) [root@hadoop11 airtest]# python -m airtest run /root/airtest/untitled.air --device Android://127.0.0.1:5037/192.168.0.103:5555?cap_method=JAVACAP&&ori_method=ADBORI&&touch_method=ADBTOUCH  --log /log
do not save log
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 get-state
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 wait-for-device
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell getprop ro.build.version.sdk
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell dumpsys activity top ; echo ---$?---
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---
[04:10:21][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 288
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell settings get secure default_input_method ; echo ---$?---
[04:10:21][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell ime list -a ; echo ---$?---
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell dumpsys package com.netease.open.pocoservice ; echo ---$?---
installed version is 41, installer version is 41. force_reinstall=False
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell dumpsys package com.netease.open.pocoservice.test ; echo ---$?---
installed version is 0, installer version is 0. force_reinstall=False
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 forward --no-rebind tcp:15606 tcp:10080
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 forward --no-rebind tcp:18150 tcp:10081
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell ps ; echo ---$?---
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell am force-stop com.netease.open.pocoservice ; echo ---$?---
[04:10:22][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell am start -n com.netease.open.pocoservice/.TestActivity ; echo ---$?---
[04:10:23][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[04:10:25][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell input keyevent HOME ; echo ---$?---
[04:10:25][INFO]<airtest.core.api> Try finding:
Template(/root/airtest/untitled.air/tpl1572060761237.png)
[04:10:25][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---
[04:10:25][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 288
[04:10:25][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 forward --no-rebind tcp:19713 localabstract:javacap_19713
[04:10:25][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell pm path com.netease.nie.yosemite ; echo ---$?---
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_19713 -lazy 2>&1
[04:10:26][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_19713'
[04:10:26][DEBUG]<airtest.core.android.javacap> (1, 3, 0, 900, 1600, 0, 0, 0, 1)
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell ls /data/local/tmp/minicap ; echo ---$?---
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[04:10:26][DEBUG]<airtest.core.android.minicap> WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
version:5
[04:10:26][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->5
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell rm /data/local/tmp/minicap*
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell getprop ro.product.cpu.abi
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell getprop ro.build.version.preview_sdk
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell getprop ro.build.version.release
[04:10:26][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 push /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/stf_libs/x86/minicap /data/local/tmp/minicap
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 push /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/stf_libs/minicap-shared/aosp/libs/android-22/x86/minicap.so /data/local/tmp/minicap.so
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[04:10:27][INFO]<airtest.core.android.minicap> minicap installation finished
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/root/myproject/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/root/airtest/untitled.air/untitled.py", line 12, in <module>
    wait(Template(r"tpl1572060761237.png", record_pos=(0.001, -0.563), resolution=(900, 1600)))
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/core/api.py", line 397, in wait
    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=intervalfunc)
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/core/cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/android.py", line 235, in snapshot
    if ensure_orientation and self.display_info["orientation"]:
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/android.py", line 527, in display_info
    self._display_info = self.get_display_info()
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 6.166s

FAILED (errors=1)
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 forward --remove tcp:15606
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 forward --remove tcp:18150
[04:10:27][DEBUG]<airtest.core.android.adb> /root/myproject/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s 192.168.0.103:5555 forward --remove tcp:19713
(venv) [root@hadoop11 airtest]#

**Comment by yimelia** [comment]
参考文档：https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2
可能需要添加转义符号，mac下是添加`\` ，你可以试一下

**Comment by 93631830** [comment]
确实是需要加转义符，可以了，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yimelia"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 上午9:53
收件人:&nbsp;"AirtestProject/AirtestIDE"<AirtestIDE@noreply.github.com&gt;;
抄送:&nbsp;"老猫"<93631830@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirtestProject/AirtestIDE] 在centos 使用python命令行运行脚本，用图片识别功能时执行报错 (#580)




参考文档：https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2
 可能需要添加转义符号，mac下是添加\ ，你可以试一下
