### ISSUE TITLE
红米5A（Redmi 5A）手机在AirtestIDE 点击connect时，出现报错

### ISSUE THREAD

**Issue by lsq4590578** [AirtestProject/AirtestIDE#606]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
红米5A（Redmi 5A）手机在AirtestIDE 点击connect时，出现报错

**复现步骤：**

**python 版本:** `python3.x`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 7.1.2]
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

报错信息：
jp.co.cyberagent.stf.rotationwatcher
C:\Users\klxx\Desktop\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 33b68c47d050 install -r C:\Users\klxx\Desktop\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\apks\RotationWatcher.apk
Traceback (most recent call last):
  File "airtest\core\android\rotation.py", line 40, in _install_and_setup
    apk_path = self.adb.path_app(ROTATIONWATCHER_PACKAGE)
  File "airtest\core\android\adb.py", line 1162, in path_app
    raise AirtestError('package not found, output:[%s]' % output)
airtest.core.error.AirtestError: 'package not found, output:[]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 162, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 87, in __init__
  File "app\plugins\device\android\android_phone.py", line 192, in startFrameStream
  File "airtest\utils\snippet.py", line 104, in ready_func
    method()
  File "airtest\core\android\rotation.py", line 61, in start
    self._install_and_setup()
  File "airtest\core\android\rotation.py", line 42, in _install_and_setup
    self.adb.install_app(ROTATIONWATCHER_APK, ROTATIONWATCHER_PACKAGE)
  File "airtest\core\android\adb.py", line 568, in install_app
    out = self.cmd(cmds)
  File "airtest\core\android\adb.py", line 187, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[] stderr[adb: failed to install C:\Users\klxx\Desktop\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\apks\RotationWatcher.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
]

**Comment by yimelia** [comment]
请查阅文档：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4

![image](https://user-images.githubusercontent.com/6896468/69113547-42dc0180-0abe-11ea-8321-dac85350598b.png)
