### ISSUE TITLE
分别启动手机和模拟器的app  手机屏幕只是闪了一下

### ISSUE THREAD

**Issue by donyu123** [AirtestProject/AirtestIDE#620]
**#手机ip
device_1=connect_device('android:///57f63c1d')
#模拟器ip
device_2=connect_device('android:///127.0.0.1:7555')

poco_1=AndroidUiautomationPoco(device_1, use_airtest_input=True, screenshot_each_action=False)

poco_2=AndroidUiautomationPoco(device_2, use_airtest_input=True, screenshot_each_action=False)
#手机app
poco_1(start_app("com.max.xiaoheihe"))
#模拟器app
poco_2(start_app("com.max.xiaoheihe"))**

**Comment by yimelia** [comment]
1. 首先，请多查阅文档了解这两个库的用法，以及每个接口的参数
![image](https://user-images.githubusercontent.com/6896468/69507173-8fb35280-0f6c-11ea-96c3-4f4597046839.png)
https://airtest.doc.io.netease.com/IDEdocs/record_script/how_to_get_started/

也就是说，start_app接口请单独使用，不要传到poco对象里

2. 如果start_app单独调用时报错了，请自行阅读报错信息来排查错误，或者贴出具体的报错信息，否则无法帮助到你

**Comment by donyu123** [comment]
但是我用其他方式启动app 比如text='xxx' 或者元素 都会报错 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yimelia** [comment]
你的用法错了，请认真查看文档范例，谢谢。
如果要贴出报错log，请贴出完整的内容，以及完整的代码内容。

**Comment by donyu123** [comment]
**from airtest.core.api import connect_device
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
device_1 = connect_device('android:///串号1')
device_2 = connect_device('android:///串号2')
device_3 = connect_device('android:///串号3')
poco_1 = AndroidUiautomationPoco(device_1, use_airtest_input=True, screenshot_each_action=False)
poco_2 = AndroidUiautomationPoco(device_2, use_airtest_input=True, screenshot_each_action=False)
poco_3 = AndroidUiautomationPoco(device_3, use_airtest_input=True, screenshot_each_action=False)
poco_1(text='微信').click()
poco_2(text='微信').click()
poco_3(text='微信').click()**

我这种方式 使用得方式不对吗 大佬 现在是 我用上面的方式  实现会报刚才我发的错误  所有才试着start_app 的方式尝试    我打印了 poco_1 和 poco_2的 确实是俩个设备 但是我用这俩设备 去启动 就不可以了   这种方式是我在网上搜的

**Comment by donyu123** [comment]
官网的文档 是 切换设备  稍微有点麻烦 所以我想试着这么弄

**Comment by yimelia** [comment]
1. 你最早发的代码是错误的，就是 `poco_1(start_app("com.max.xiaoheihe"))` 这个写法是错的。
我不知道你后面改成了什么样子，所以才叫你发**完整的代码**，不然不知道到底是什么问题

2. 请发**完整的报错log**出来，不然不知道到底是哪个地方的问题

3. 在尝试切换设备之前，请先确认你的代码在单台设备上是可以正确运行的，然后再考虑多台设备的问题，否则可能会定位不到真正的问题所在。

4. 遇到问题请尽量查阅文档，具体的逻辑请自行编写。

**Comment by donyu123** [comment]
**ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "C:\Users\admin\Desktop\Demo4.air\Demo4.py", line 21, in <module>
    poco_1(text="小黑盒").click()
  File "D:\AirTest\AirtestIDE_2019-09-11_py3_win64\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\AirTest\AirtestIDE_2019-09-11_py3_win64\poco\proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "D:\AirTest\AirtestIDE_2019-09-11_py3_win64\poco\pocofw.py", line 252, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "D:\AirTest\AirtestIDE_2019-09-11_py3_win64\poco\utils\airtest\input.py", line 76, in click
    pos = self.get_target_pos(x, y)
  File "D:\AirTest\AirtestIDE_2019-09-11_py3_win64\poco\utils\airtest\input.py", line 54, in get_target_pos
    offsetx, offsety, pw, ph = self._get_touch_resolution()
  File "D:\AirTest\AirtestIDE_2019-09-11_py3_win64\poco\utils\airtest\input.py", line 66, in _get_touch_resolution
    w, h = current_device().get_current_resolution()
  File "airtest\core\android\android.py", line 560, in get_current_resolution
  File "airtest\core\android\android.py", line 527, in display_info
  File "airtest\core\android\android.py", line 546, in get_display_info
  File "airtest\utils\snippet.py", line 106, in ready_func
  File "airtest\core\android\minicap.py", line 149, in get_display_info
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 9.348s

FAILED (errors=1)**

**实现方式
#手机ip
device_1=connect_device('android://127.0.0.1:5037/57f63c1d')
#模拟器ip
device_2=connect_device('android://127.0.0.1:5037/127.0.0.1:7555')

poco_1=AndroidUiautomationPoco(device_1, use_airtest_input=True, screenshot_each_action=False)

poco_2=AndroidUiautomationPoco(device_2, use_airtest_input=True, screenshot_each_action=False)
#手机
poco_1(text="小黑盒").click()
#模拟器
poco_2(text="小黑盒").click()
print(G.DEVICE_LIST)**
 单个脚本可以启动

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2

**Comment by donyu123** [comment]
我自己在找找吧  大佬提供的文档我看过了 都试了

**Comment by yimelia** [comment]
device_2=connect_device('android://127.0.0.1:5037/127.0.0.1:7555?cap_method=JAVACAP&&ori_method=ADBORI')

**Comment by donyu123** [comment]
多谢大佬指点  已经处理好了
