### ISSUE TITLE
python运行airtest录制的airtest-selenium脚本报错

### ISSUE THREAD

**Issue by chaoqu1** [AirtestProject/AirtestIDE#635]
python d:\register.py
Traceback (most recent call last):
  File "D:\register.py", line 8, in <module>
    from airtest_selenium.proxy import WebChrome
  File "F:\python37\lib\airtest_selenium\__init__.py", line 1, in <module>
    from .proxy import WebChrome, Element
  File "F:\python37\lib\airtest_selenium\proxy.py", line 13, in <module>
    from pynput.mouse import Controller, Button
ModuleNotFoundError: No module named 'pynput'

**Comment by yimelia** [comment]
请自行在本地python环境中安装所需要的第三方库
