### ISSUE TITLE
【OPPO R17机型不兼容】

### ISSUE THREAD

**Issue by lpghappy** [AirtestProject/AirtestIDE#661]
H:\Program Files (x86)\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s bb888d13 wait-for-device
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 351, in run
  File "airtest\core\api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "airtest\core\api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "airtest\core\android\android.py", line 39, in __init__
    self.adb.wait_for_device()
  File "airtest\core\android\adb.py", line 297, in wait_for_device
    raise DeviceConnectionError("device not ready")
airtest.core.error.DeviceConnectionError: 'device not ready'

ADB指令执行失败，可能需要修改部分手机设置才能使用，请访问[帮助文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html)查看如何设置。

**Comment by yimelia** [comment]
可能是这个问题：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#airtestadb
特别是win7系统下，用了本地python来跑的话，最好是自己把所有的adb.exe都替换成同一个
