### ISSUE TITLE
无法启动airtest

### ISSUE THREAD

**Issue by wyuan652197552** [AirtestProject/AirtestIDE#669]
兼容模式启动，报错如下：
D:\AirtestIDE_2019-09-11_py3_win64>AirtestIDE.exe
Info: filter not set, use raven.filter.FullPassFilter instead.
setting OPENGL=software...

**Comment by EraChen233** [comment]
这个是正常输出，不是报错。
麻烦提供更多信息，以便我们定位问题

**Comment by deardy** [comment]
loading config from : C:\Users\Administrator\AppData\Local\AirtestIDE\AirtestIDE\user.json
[20048:24000:0425/110705.031:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
Traceback (most recent call last):
  File "jedi\cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\parso\grammar.py", line 236, in load_grammar
KeyError: 'D:\\AirtestIDE\\parso\\python\\grammar39.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\parso\grammar.py", line 239, in load_grammar
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AirtestIDE\\parso\\python\\grammar39.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\editor\plugin.py", line 241, in init_jedi_env
  File "jedi\api\__init__.py", line 494, in preload_module
    Script(s, 1, len(s), None, environment=environment).completions()
  File "jedi\api\__init__.py", line 108, in __init__
    project, environment=environment, script_path=self.path
  File "jedi\evaluate\__init__.py", line 95, in __init__
    self.grammar = environment.get_grammar()
  File "jedi\cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "jedi\api\environment.py", line 36, in get_grammar
    return parso.load_grammar(version=version_string)
  File "site-packages\parso\grammar.py", line 250, in load_grammar
  File "site-packages\parso\grammar.py", line 246, in load_grammar
NotImplementedError: Python version 3.9 is currently not supported.

ARB::createContext: wglCreateContextAttribsARB() failed (GL error code: 0x0) for format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)), shared context: 0x1 (操作成功完成。)
GDI::createContext: wglCreateContext failed. (操作成功完成。)
Unable to create a GL Context.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.
