### ISSUE TITLE
OPPO ACE无法连接

### ISSUE THREAD

**Issue by wtgadtdg** [AirtestProject/AirtestIDE#673]
bug描述
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 shell ls /data/local/tmp/minicap
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 shell ls /data/local/tmp/minicap.so
install minicap
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 shell getprop ro.product.cpu.abi
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 shell getprop ro.build.version.preview_sdk
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 shell getprop ro.build.version.release
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 push E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\stf_libs\arm64-v8a\minicap /data/local/tmp/minicap
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 shell chmod 755 /data/local/tmp/minicap
E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 39992bf0 push E:\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so /data/local/tmp/minicap.so
Traceback (most recent call last):
  File "app\plugins\device\android\android_client.py", line 162, in loadConnectedPhones
  File "app\plugins\device\android\android_phone.py", line 83, in __init__
  File "app\plugins\device\android\android_phone.py", line 111, in _initDev
  File "airtest\core\android\android.py", line 527, in display_info
    self._display_info = self.get_display_info()
  File "airtest\core\android\android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "airtest\utils\snippet.py", line 104, in ready_func
    method()
  File "airtest\utils\snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 86, in install_or_upgrade
    self.install()
  File "airtest\core\android\minicap.py", line 132, in install
    self.adb.push(path, "%s/minicap.so" % device_dir)
  File "airtest\core\android\adb.py", line 429, in push
    self.cmd(["push", local, remote], ensure_unicode=False)
  File "airtest\core\android\adb.py", line 187, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'E:\\AirtestIDE_2019-09-10_py3_win64\\AirtestIDE_2019-09-11_py3_win64\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']
**复现步骤：**

**python 版本:** `python3.6`

**操作系统:** `Windows10 专业版`

**手机设备信息:**
 - 手机型号:OPPO ACE
 - Android系统版本号:  Android 10

- AirtestIDE版本号：1.2.2

**截屏**
![Uploading image.png…]()

**Comment by EraChen233** [comment]
Android 10 暂未做支持，因此可能会出现一些未知的错误

**Comment by yimelia** [comment]
Android10可以等待下个版本的更新
