### ISSUE TITLE
1.2.3版本的airtestIDE，win10打不开

### ISSUE THREAD

**Issue by a1023182899** [AirtestProject/AirtestIDE#700]
报错如下：
C:\Users\swt\Downloads\AirtestIDE_2020-01-20_py3_win64\AirtestIDE_2020-01-20_py3_win64_137\AirtestIDE_2020-01-20_py3_win64>AirtestIDE.exe
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 41, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\main_window.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\login_user_info.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\plugins\core\plugin.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\login_widget.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\token\ide_token.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\token\hardware_uuid.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\wmi.py", line 157, in <module>
  File "site-packages\win32com\client\__init__.py", line 72, in GetObject
  File "site-packages\win32com\client\__init__.py", line 87, in Moniker
pywintypes.com_error: (-2147023838, '无法启动服务，原因可能是已被禁用或与其相关联的设备没有启动。', None, None)
[15024] Failed to execute script AirtestIDE

**Comment by zhouyf1600717507** [comment]
这个问题解决了吗？我也遇到同样得问题
