### ISSUE TITLE
运行android设备ide可以通过，python代码运行报错；

### ISSUE THREAD

**Issue by duxia001** [AirtestProject/AirtestIDE#707]
报错内容：
[05:17:27][INFO]<airtest.core.api> Try finding:
Template(homePage.air/tpl1582775848315.png)
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell pm path jp.co.cyberagent.stf.rotationwatcher
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-DgSYgAFDQNcPr6KfQxs6xA==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell ls /data/local/tmp/minicap
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell ls /data/local/tmp/minicap.so
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[05:17:27][DEBUG]<airtest.core.android.minicap> version:5
[05:17:27][DEBUG]<airtest.core.android.minicap> skip install minicap
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 forward --no-rebind tcp:12230 localabstract:minicap_12230
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell dumpsys window displays
[05:17:27][DEBUG]<airtest.core.android.adb> /Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s ad3942d9 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_12230' -P 1080x2160@1080x2160/0 -l 2>&1
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 15998'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2160@1080x2160/0'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Vector<> have different types (this=0x7fc74f1ec0, rhs=0x7fc74f1fe0)'
[05:17:28][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Aborted'
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/duxiao/uitest-ios/homePage.air/homePage.py", line 29, in <module>
    wait(Template(r"tpl1582775848315.png", record_pos=(-0.385, -0.031), resolution=(1080, 1440), threshold=0.6))
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/api.py", line 397, in wait
    pos = loop_find(v, timeout=timeout, interval=interval, intervalfunc=intervalfunc)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/android.py", line 218, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 339, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 233, in get_stream
    stopped = next(gen)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 247, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "/Users/duxiao/test.air/venv/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 312, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout

**Comment by yimelia** [comment]
如果你在IDE中连接设备时，需要勾选use javacap才能链接的话，在运行脚本时也需要指定这个参数，参考：https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2
