### ISSUE TITLE
版本 v1.2.3Windows(64bit),win10启动报错，无法打开工具首页

### ISSUE THREAD

**Issue by littilefan** [AirtestProject/AirtestIDE#714]
C:\Users\fanxf\Downloads\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64>AirtestIDE.exe
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 41, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\main_window.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\login_user_info.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\plugins\core\plugin.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\login_widget.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\token\ide_token.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\token\hardware_uuid.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\wmi.py", line 158, in <module>
  File "site-packages\wmi.py", line 147, in __init__
pywintypes.com_error: (-2147319779, '库没有注册。', None, None)
[6868] Failed to execute script AirtestIDE

**Comment by yimelia** [comment]
尝试双击目录下的兼容模式启动.bat文件来启动看看是否能够启动？

**Comment by littilefan** [comment]
C:\Users\fanxf\Downloads\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64>兼容模式启动.bat

C:\Users\fanxf\Downloads\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64>rem set AIRTESTIDE_OPENGL=angle

C:\Users\fanxf\Downloads\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64>set AIRTESTIDE_OPENGL=software

C:\Users\fanxf\Downloads\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64>AirtestIDE.exe
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 41, in main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\main_window.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\login_user_info.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\plugins\core\plugin.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\login_widget.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\token\ide_token.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\widgets\login\token\hardware_uuid.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "e:\project\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\wmi.py", line 158, in <module>
  File "site-packages\wmi.py", line 147, in __init__
pywintypes.com_error: (-2147319779, '库没有注册。', None, None)
[13356] Failed to execute script AirtestIDE
