### ISSUE TITLE
红米K20pro 无法链接

### ISSUE THREAD

**Issue by tdq851119** [AirtestProject/AirtestIDE#718]
手机链接正常，USB安装权限和调试都打开。第三方应用安装已允许。安装微型服务报错如下

[10:29:39][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Aborted'
[10:29:44][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 483, in run
  File "app\plugins\device\android\util.py", line 474, in _get_android_frame
  File "airtest\core\android\minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 339, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "airtest\core\android\minicap.py", line 233, in get_stream
    stopped = next(gen)
  File "airtest\core\android\minicap.py", line 247, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "airtest\core\android\minicap.py", line 312, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout

[Warning] The current device is unplugged!
[10:29:44][DEBUG]<airtest.core.android.adb> C:\Users\MSI\Desktop\AirtestIDE_2019-09-10_py3_win64\AirtestIDE_2019-09-11_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices

**Comment by yimelia** [comment]
勾选use javacap后再连接即可
