### ISSUE TITLE
airtest控制台运行报编码错误

### ISSUE THREAD

**Issue by chadwi** [AirtestProject/AirtestIDE#73]
**运行 airtest run "autotest.air" --device Android:///
报错如下，请问是什么原因？在IDE环境下可以正常运行，切换.py文件为utf-8编码也不行**

======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\airtest\cli\runner.py", line 84, in runTest
    exec(compile(code, pyfilepath.encode(sys.getfilesystemencoding()), 'exec')) in self.scope
  File "D:\Projects\AutoTest\autotest.air\autotest.py", line 19, in <module>
    poco = UnityPoco()
  File "d:\python27\lib\site-packages\poco\drivers\unity3d\unity3d_poco.py", line 137, in __init__
    agent = UnityPocoAgent(addr, unity_editor, connect_default_device)
  File "d:\python27\lib\site-packages\poco\drivers\unity3d\unity3d_poco.py", line 55, in __init__
    current_device().adb.forward("tcp:%s" % addr[1], "tcp:5001", False)
  File "d:\python27\lib\site-packages\airtest\core\android\adb.py", line 440, in forward
    self.cmd(cmds + [local, remote])
  File "d:\python27\lib\site-packages\airtest\core\android\adb.py", line 172, in cmd
    stderr = stderr.decode(get_std_encoding(sys.stderr))
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 86-87: illegal multibyte sequence

----------------------------------------------------------------------
Ran 1 test in 6.113s

**Comment by Meteorix** [comment]
@chadwi 

这应该是你的``adb forward``指令有报错，如果可以的话，在cmd里面试试``adb forward tcp:5001 tcp:5001``，贴一下输出信息

**Comment by chadwi** [comment]
@Meteorix 补上前面一段log

[05:26:08][DEBUG]<airtest.core.android.adb> d:\python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 10cd70a0 shell ps ; echo ---$?---
[05:26:08][DEBUG]<airtest.core.android.adb> d:\python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 10cd70a0 shell am force-stop com.netease.open.pocoservice ; echo ---$?---
[05:26:09][DEBUG]<airtest.core.android.adb> d:\python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 10cd70a0 shell am start -n com.netease.open.pocoservice/.TestActivity ; echo ---$?---
[05:26:10][DEBUG]<airtest.core.android.adb> d:\python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 10cd70a0 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[05:26:12][DEBUG]<airtest.core.android.adb> d:\python27\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 10cd70a0 forward tcp:5001 tcp:5001
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\airtest\cli\runner.py", line 84, in runTest
    exec(compile(code, pyfilepath.encode(sys.getfilesystemencoding()), 'exec')) in self.scope
  File "D:\Projects\AutoTest\autotest.air\autotest.py", line 19, in <module>
    poco = UnityPoco()

另外，在命令行下运行  
C:\Users\Chadwi>adb forward tcp:5001 tcp:5001
error: cannot bind listener: cannot bind to 127.0.0.1:5001: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)

**Comment by Meteorix** [comment]
这个是你的5001端口被占用了，最好能查查看是什么进程占用的

先试试``adb forward --list``看看是不是adb自己占用的

**Comment by chadwi** [comment]
查了 是 adb 占用了，结束进程，再用 adb forward tcp:5001 tcp:5001
就啥也不显示了，无任何信息，直接返回命令行

**Comment by rockywhisper** [comment]
@chadwi  结束进程后再命令行跑下脚本？

**Comment by chadwi** [comment]
@rockywhisper 结束 adb进程，再运行脚本，就可以了，thanks
