### ISSUE TITLE
airtestide连接夜神模拟器错误

### ISSUE THREAD

**Issue by javajiang** [AirtestProject/AirtestIDE#738]
**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: Android 5.1
 - (别的信息)

adb connect能够成功，但airtestide连接失败，按照教程里的解决方法，并没有发现模拟器有usb连接选项

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

### 
![Screenshot_2020-04-04-01-16-00](https://user-images.githubusercontent.com/20487883/78388021-e1eb3b00-7612-11ea-8ee2-e71bf69aa1d8.png)
`copy adb39.exe failed...
Info: filter not set, use raven.filter.FullPassFilter instead.
loading config from : ['C:\\Users\\Administrator\\AppData\\Local\\AirtestIDE\\Ai
rtestIDE\\user.json']
qt.qpa.gl: Unable to disable rotation.
[12:58:05][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe devices
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
[12:58:11][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 get-state
[12:58:11][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 wait-for-device
[12:58:11][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell getprop ro.build.version.sdk
[12:58:11][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell dumpsys display
[12:58:11][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell dumpsys SurfaceFlinger ; echo ---$?---
[12:58:12][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell getevent -p ; echo ---$?---
[12:58:12][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell pm path jp.co.cyberagent.stf.rotationwat
cher ; echo ---$?---
[12:58:13][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell export CLASSPATH=/data/app/jp.co.cyberag
ent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent
.stf.rotationwatcher.RotationWatcher
[12:58:13][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell dumpsys package com.netease.nie.yosemite
 ; echo ---$?---
[12:58:13][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell dumpsys window windows ; echo ---$?---
[12:58:14][INFO]<airtest.core.android.yosemite> local version code is 300, insta
lled version code is None
[12:58:14][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 install -t -g -r D:\airtest\AirtestIDE_2020-01
-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\apks\Y
osemite.apk
[12:58:14][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell getprop ro.product.manufacturer
[12:58:17][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 forward --no-rebind tcp:19804 localabstract:ja
vacap_19804
[12:58:17][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell getprop ro.product.model
[12:58:17][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell getprop ro.product.manufacturer
[12:58:17][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell pm path com.netease.nie.yosemite ; echo
---$?---
[12:58:18][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe -P 5037 -s 127.0.0.1:62001 shell getprop ro.product.model
[12:58:18][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 485, in run
  File "app\plugins\device\android\util.py", line 478, in _get_android_frame
  File "airtest\core\android\javacap.py", line 101, in get_frame_from_stream
    return self.frame_gen.send(None)
  File "airtest\core\android\javacap.py", line 61, in get_frames
    proc, nbsp, localport = self._setup_stream_server()
  File "airtest\utils\snippet.py", line 107, in ready_func
    return func(inst, *args, **kwargs)
  File "airtest\core\android\javacap.py", line 36, in _setup_stream_server
    apkpath = self.adb.path_app(self.APP_PKG)
  File "airtest\core\android\adb.py", line 1168, in path_app
    raise AirtestError('package not found, output:[%s]' % output)
airtest.core.error.AirtestError: 'package not found, output:[]'

[Warning] The current device is unplugged!
[12:58:19][DEBUG]<airtest.core.android.adb> D:\airtest\AirtestIDE_2020-01-21_py3
_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\a
db.exe devices
`

**Comment by yimelia** [comment]
找一下看看有没有类似于 允许通过USB安装应用 的选项，需要打开。
报错是因为想要往模拟器中安装yosemite.apk失败了。

**Comment by javajiang** [comment]
> 找一下看看有没有类似于 允许通过USB安装应用 的选项，需要打开。
> 报错是因为想要往模拟器中安装yosemite.apk失败了。

您好，在模拟器里没找到模拟器有usb连接选项，请问下应该怎么处理

**Comment by yimelia** [comment]
可以直接把AirtestIDE目录里的yosemite.apk（直接在文件夹里搜一下），手工安装到模拟器里

**Comment by javajiang** [comment]
> 找一下看看有没有类似于 允许通过USB安装应用 的选项，需要打开。
> 报错是因为想要往模拟器中安装yosemite.apk失败了。

您好，谢谢您的答案，问题已经解决，还有个问题麻烦看下 ，poco定位不准，有时poco辅助窗口UI树叶不刷新，定位是前一页的定位
