### ISSUE TITLE
华为(HUAWEI Mate 20) 无法使用Poco Log查看窗回报错误 minitouch setup timeout

### ISSUE THREAD

**Issue by ErickJiang** [AirtestProject/AirtestIDE#741]
分类
测试开发环境AirtestIDE使用问题

详细描述问题bug：
华为(HUAWEI Mate 20) 无法使用Poco Log查看窗回报错误 minitouch setup timeout

复现步骤：
1. 使用adb与adbtouch开启手机画面
2. 新增挡案 .py纯Python(高级用户)
3. 打开poco辅助android
4. 新增poco指令
5. 启动执行

python 版本: python3.x

操作系统: Windows10 64bit

手机设备信息:
 - 型号: HMA-AL00
 - 版本编号: 10.0.0.185(C00E74R1P8patch01) GPU Turbo
 - EMUI版本: 10.0.0
 - Android版本: 10

**其他相关信息补充**
- AirtestIDE版本号： 1.2.3 
- 执行code :
#######################################################################
__author__ = "Erick.Jiang"
from airtest.core.api import *
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
from airtest.cli.parser import cli_setup

if not cli_setup():
    auto_setup(__file__, logdir=True, devices=[
            "Android://127.0.0.1:5037/66J0218C21003729?touch_method=ADBTOUCH",
    ])
# script content
print("start...")
poco(text="首页").click()
# generate html report
# from airtest.report.report import simple_report
# simple_report(__file__, logpath=True)
#######################################################################

- 错误讯息 :
#######################################################################
[Start running..]
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 wait-for-device
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell getprop ro.build.version.sdk
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys activity top
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys package com.netease.nie.yosemite
[04:50:59][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 300
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell settings get secure default_input_method
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell ime list -a
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys package com.netease.open.pocoservice
installed version is 41, installer version is 41. force_reinstall=False
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --no-rebind tcp:12651 tcp:10080
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --no-rebind tcp:16514 tcp:10081
[04:50:59][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell ps
no cmdline args
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 66J0218C21003729 wait-for-device
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 66J0218C21003729 shell getprop ro.build.version.sdk
[04:51:00][WARNING]<airtest.core.api> Device:66J0218C21003729 updated <airtest.core.android.android.Android object at 0x03777730> -> <airtest.core.android.android.Android object at 0x112FB0F0>
start...
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell ls /data/local/tmp/minicap
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell ls /data/local/tmp/minicap.so
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[04:51:00][DEBUG]<airtest.core.android.minicap> version:6
[04:51:00][DEBUG]<airtest.core.android.minicap> skip install minicap
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys window displays
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell pm path jp.co.cyberagent.stf.rotationwatcher
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-QqEyXTJuKUxTB3KZpoJYUw==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --no-rebind tcp:14474 localabstract:minicap_14474
[04:51:00][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys window displays
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_14474' -P 1080x2244@1080x2244/0 -l 2>&1
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 13971'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2244@1080x2244/0'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:241) Creating SurfaceComposerClient'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:244) Performing SurfaceComposerClient init check'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:255) Creating virtual display'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:261) Creating buffer queue'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:264) Setting buffer options'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:268) Creating CPU consumer'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:272) Creating frame waiter'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_29.cpp:276) Publishing virtual display'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 7365636 bytes for JPG encoder'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[04:51:01][DEBUG]<airtest.core.android.minicap> (1, 24, 13971, 1080, 2244, 1080, 2244, 0, 2)
[04:51:01][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell getprop ro.product.cpu.abi
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell getprop ro.build.version.sdk
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell ls /data/local/tmp/minitouch
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell ls -l /data/local/tmp/minitouch
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell rm /data/local/tmp/minitouch*
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 push C:\\Users\\erick.jiang\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\arm64-v8a\\minitouch /data/local/tmp/minitouch
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell chmod 755 /data/local/tmp/minitouch
[04:51:01][INFO]<airtest.core.android.minitouch> install_minitouch finished
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell dumpsys window displays
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --no-rebind tcp:18586 localabstract:minitouch_18586
[04:51:01][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 shell /data/local/tmp/minitouch -n 'minitouch_18586' 2>&1
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'open: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event0 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event1 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event5 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event3 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event2 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event4 for inspectionopen: Permission denied'
[04:51:01][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/mice for inspectionUnable to find a suitable touch device'
Traceback (most recent call last):
  File "D:\AutoTest\OASystemTest\android\ID.py", line 20, in <module>
    poco(text="首\u9875").click()
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\poco\proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\poco\pocofw.py", line 252, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\poco\utils\airtest\input.py", line 77, in click
    touch(pos, duration=self.default_touch_down_duration)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\api.py", line 262, in touch
    G.DEVICE.touch(pos, **kwargs)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\android.py", line 340, in touch
    self.minitouch.touch(pos, duration=duration)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\utils\snippet.py", line 104, in ready_func
    method()
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\utils\snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\minitouch.py", line 51, in install_and_setup
    self.setup_server()
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\minitouch.py", line 143, in setup_server
    raise RuntimeError("minitouch setup timeout")
RuntimeError: minitouch setup timeout
[04:51:06][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --remove tcp:12651
[04:51:06][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --remove tcp:16514
[04:51:06][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --remove tcp:14474
[04:51:06][DEBUG]<airtest.core.android.adb> C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 66J0218C21003729 forward --remove tcp:18586
[04:51:06][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception ignored in: <function RpcObjectProxy.__del__ at 0x112CFDF8>
Traceback (most recent call last):
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hrpc\client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "C:\Users\erick.jiang\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hrpc\transport\http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=16514): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11E03F90>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))

[Finished]
#######################################################################

**截屏**
![image](https://user-images.githubusercontent.com/57085981/78769846-6a296180-79c0-11ea-8843-0316594f3940.png)

**Comment by yimelia** [comment]
Android10版本，将AirtestIDE和本地python环境中的airtest都更新至最新版即可

**Comment by ErickJiang** [comment]
都更新最新版后可以正常运行了，谢谢说明。
