### ISSUE TITLE
firebase 打包安装后，最后一步运行adb命令出错

### ISSUE THREAD

**Issue by githuyong** [AirtestProject/AirtestIDE#744]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
按文档做firebase测试，安装apk到手机后，
运行adb.exe shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner 
如下：
PS C:\Temp\Tools> .\adb.exe shell am instrument -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

org.kivy.android.ExampleInstrumentedTest:

一直卡在这

然后有错误：
Error in launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
java.lang.RuntimeException: Could not launch intent Intent { flg=0x14000000 cmp=com.netease.open.airbase/org.kivy.android.PythonActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1586695243951 and now the last time the queue went idle was: 1586695243951. If these numbers are the same your activity might be hogging the event queue.
        at android.support.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:419)
        at android.support.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:332)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2089)

**复现步骤：**
代码是想测试打开百度地图app
air开头代码：

# -*- encoding=utf8 -*-
__author__ = "yu"
from airtest.core.api import *
auto_setup(__file__)
start_app("com.baidu.BaiduMap")

**python 版本:** `python3.x`
3.7, 32bit

**操作系统:** `Windows7 64bit`
win10 64bit

**手机设备信息:**
 - 手机型号: 小米6  
 - Android系统版本号: MIUI 10.3稳定版 ， Android 8.0
 - (别的信息)

**其他相关信息补充**
 win10运行， python3.7 32bit
- AirtestIDE版本号：v1.2.3

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
![image](https://user-images.githubusercontent.com/19883408/79071244-4db55e00-7d0d-11ea-87ff-4e4daa55da37.png)
![Uploading image.png…]()

**Comment by yimelia** [comment]
目前无法看出问题，可以贴出脚本的完整代码吗？
或者，将脚本代码删除掉主体内容，只添加一两条点击语句，看看是否能执行成功
目前放出的apk打包功能里，不支持poco，如果用了poco的话是无法使用的

**Comment by githuyong** [comment]
> 目前无法看出问题，可以贴出脚本的完整代码吗？
> 或者，将脚本代码删除掉主体内容，只添加一两条点击语句，看看是否能执行成功
> 目前放出的apk打包功能里，不支持poco，如果用了poco的话是无法使用的

我重新打包，现在都报 “目标目录无效”， 打不上包了，
我看firebase 有个 
"打包时，因为涉及到文件删除操作，所以不要使用目标包体的目录（有些用户习惯性直接在生成包体的目录打开命令行安装，会导致无法进行下一次打包）"
这是什么意思呢？没明白
![image](https://user-images.githubusercontent.com/19883408/79096266-374fe680-7d8f-11ea-9112-c776e7df0b33.png)

**Comment by yimelia** [comment]
打包完毕后，会自动开启一个windows窗口打开apk所在的路径，在下一次打包之前，最好不要占用着这个windows窗口（关掉它，并且如果你在这个窗口中打开过cmd的话也要关掉）

**Comment by githuyong** [comment]
> 打包完毕后，会自动开启一个windows窗口打开apk所在的路径，在下一次打包之前，最好不要占用着这个windows窗口（关掉它，并且如果你在这个窗口中打开过cmd的话也要关掉）

这个目录名称无效，原来是我是新建得python文件，不是air文件，打包apk好像只能是air文件是吧？

然后最后一步不能运行，我换个moto得手机，发现可以运行，所以估计是小米手机本身有设置没对。

最后想咨询一下，如果ide里面是建的python文件，可以打成一个可执行包吗？如果可以，spec文件需要怎么打包，有样例吗？

**Comment by yimelia** [comment]
> 打包apk好像只能是air文件是吧？

目前是的

> 如果ide里面是建的python文件，可以打成一个可执行包吗？如果可以，spec文件需要怎么打包，有样例吗？

我们没有试过，暂时没有样例可以提供

**Comment by wenyezc** [comment]
所以，这个错咋个解决？
