### ISSUE TITLE
appium和poco无法混合使用

### ISSUE THREAD

**Issue by xhongyan** [AirtestProject/AirtestIDE#851]
airtest 和appium可以混合使用，但是poco和appium就不行

chromedriverExecutableDir： D:\auto\code\auto_common\App_Test\Common\..\ChromeDrivers\All
[11:36:27][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 wait-for-device
[11:36:27][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell getprop ro.build.version.sdk
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell dumpsys activity top

[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell dumpsys package com.netease.nie.yosemite
[11:36:28][INFO]<airtest.core.android.yosemite> local version code is 302, installed version code is 302
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell settings get secure default_input_method
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell ime list -a
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell ime enable com.netease.nie.yosemite/.ime.ImeService
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell ime set com.netease.nie.yosemite/.ime.ImeService
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell dumpsys package com.netease.open.pocoservice
installed version is 41, installer version is 41. force_reinstall=False
[11:36:28][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[11:36:29][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 forward --no-rebind tcp:16146 tcp:10080
[11:36:29][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 forward --no-rebind tcp:12414 tcp:10081
[11:36:29][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell ps -A |echo $(grep -E com.github.uiautomator)
[11:36:29][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell am force-stop com.netease.open.pocoservice
[11:36:29][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell am start -n com.netease.open.pocoservice/.TestActivity
[11:36:29][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
D:\program\python3.7.3\lib\site-packages\poco\drivers\android\uiautomation.py:285: UserWarning: [pocoservice.apk] instrumentation test server process is no longer alive
  warnings.warn("[pocoservice.apk] instrumentation test server process is no longer alive")
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:\r\nError in launch(com.netease.open.pocoservice.InstrumentedTestAsLauncher):\r\njava.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@9c87f32already registered!\r\n\tat android.os.Parcel.createException(Parcel.java:2079)\r\n\tat android.os.Parcel.readException(Parcel.java:2039)\r\n\tat android.os.Parcel.readException(Parcel.java:1987)\r\n\tat android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:427)\r\n\tat android.app.UiAutomation.connect(UiAutomation.java:241)\r\n\tat android.app.Instrumentation.getUiAutomation(Instrumentation.java:2229)\r\n\tat android.app.Instrumentation.getUiAutomation(Instrumentation.java:2186)\r\n\tat com.netease.open.pocoservice.UiAutomationConnection.get(UiAutomationConnection.java:19)\r\n\tat com.netease.open.pocoservice.ServerForHierarchyViewer.<init>(ServerForHierarchyViewer.java:48)\r\n\tat com.netease.open.pocoservice.InstrumentedTestAsLauncher.launch(InstrumentedTestAsLauncher.java:33)\r\n\tat java.lang.reflect.Method.invoke(Native Method)\r\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\r\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\r\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\r\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\r\n\tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\r\n\tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat org.junit.runners.Suite.runChild(Suite.java:128)\r\n\tat org.junit.runners.Suite.runChild(Suite.java:27)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat org.junit.runner.JUnitCore.run(JUnitCore.java:137)\r\n\tat org.junit.runner.JUnitCore.run(JUnitCore.java:115)\r\n\tat android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)\r\n\tat android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)\r\n\tat android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2258)\r\nINSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
still waiting for uiautomation ready.
[pocoservice.apk] stdout: b''
[pocoservice.apk] stderr: b''
[11:36:41][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell ps -A |echo $(grep -E uiautomator)
still waiting for uiautomation ready.
[11:36:41][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell am force-stop com.netease.open.pocoservice
D:\program\python3.7.3\lib\site-packages\poco\drivers\android\uiautomation.py:305: UserWarning: AndroidUiautomationPoco should not run together with "uiautomator". "uiautomator" will be killed.
  .format(self.__class__.__name__))
[11:36:41][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 shell kill 21708
[11:36:41][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 uninstall com.github.uiautomator

Ran 1 test in 22.887s

FAILED (errors=1)
[11:36:42][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 forward --remove tcp:16146

Error
Traceback (most recent call last):
  File "D:\program\python3.7.3\lib\site-packages\airtest\core\android\adb.py", line 371, in shell
    out = self.raw_shell(cmd)
  File "D:\program\python3.7.3\lib\site-packages\airtest\core\android\adb.py", line 329, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "D:\program\python3.7.3\lib\site-packages\airtest\core\android\adb.py", line 194, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b''] stderr[b'/system/bin/sh: kill: 21708: Operation not permitted\r\n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\program\python3.7.3\lib\site-packages\poco\drivers\android\uiautomation.py", line 309, in _kill_uiautomator
    self.adb_client.shell(['kill', pid])
  File "D:\program\python3.7.3\lib\site-packages\airtest\core\android\adb.py", line 373, in shell
    raise AdbShellError(err.stdout, err.stderr)
airtest.core.error.AdbShellError: stdout[b''] stderr[b'/system/bin/sh: kill: 21708: Operation not permitted\r\n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\program\python3.7.3\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "D:\program\python3.7.3\lib\unittest\case.py", line 615, in run
    testMethod()
  File "D:\auto\code\auto_common\App_Test\TestCase_App\Process\AirtestTestcase2.py", line 51, in test_demo
    poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
  File "D:\program\python3.7.3\lib\site-packages\poco\drivers\android\uiautomation.py", line 193, in __init__
    self._kill_uiautomator()
  File "D:\program\python3.7.3\lib\site-packages\poco\drivers\android\uiautomation.py", line 312, in _kill_uiautomator
    uninstall(self.adb_client, UiAutomatorPackage)
  File "D:\program\python3.7.3\lib\site-packages\poco\drivers\android\utils\installation.py", line 40, in uninstall
    adb_client.uninstall_app(package)
  File "D:\program\python3.7.3\lib\site-packages\airtest\core\android\adb.py", line 662, in uninstall_app
    return self.cmd(['uninstall', package])
  File "D:\program\python3.7.3\lib\site-packages\airtest\core\android\adb.py", line 194, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[Failure [DELETE_FAILED_INTERNAL_ERROR]
] stderr[]

Assertion failed
[11:36:42][DEBUG]<airtest.core.android.adb> D:\program\python3.7.3\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s S2D0218C11001483 forward --remove tcp:12414

Process finished with exit code 1

Assertion failed

Assertion failed

**Comment by yimelia** [comment]
是的，poco和appium底层用了相同的框架，是无法同时启用的

**Comment by xhongyan** [comment]
> 是的，poco和appium底层用了相同的框架，是无法同时启用的

好的，多谢

**Comment by xhongyan** [comment]
好的，感谢
