### ISSUE TITLE
Airtest Custom Python Code -  TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by MaximKitaev** [AirtestProject/AirtestIDE#877]
Hello Airtesters!) 
When I use Custom Python Path I have a strange Issue - 

I spent 1 day to solve this problem, but I did not find a solution. 

I've been changing the environment. 
I tried to pass the path to the file as a byte-object.
I decoded the picture into base64.

`TypeError: cannot use a string pattern on a bytes-like object
`
![image](https://user-images.githubusercontent.com/72766918/101734378-39f70d00-3ad1-11eb-8294-aff155b26f34.png)

I have this Issue, when i use this commands:

`swipe([0.5, 0.8], [0.5, 0.3])`
`touch(Template(r"tpl1607583450288.png", record_pos=(0.004, -0.476), resolution=(1080, 2280)),times=1, duration=0.01)`

But This command works Currectly: 

`exists(Template(r"tpl1607585362450.png", record_pos=(0.003, -0.459), resolution=(1080, 2280)))`
`wait(Template(r"tpl1607585510451.png", record_pos=(0.004, 0.476), resolution=(1080, 2280)))`

https://youtu.be/bN1sB8lFJtw - Airtest Python Example 

https://youtu.be/jZZKrX6YE3s - The Same Code with Custom Python Path - TypeError 

https://pastebin.pl/view/e4d67c59 - Error Log 

[TypeError.zip](https://github.com/AirtestProject/AirtestIDE/files/5670887/TypeError.zip)

I look forward to your help, pleas

**Comment by jay-on-zwc** [comment]
I met the same bug when I use AndroidUiautomationPoco() .
Here is my code:
```
from airtest.core.api import auto_setup
auto_setup(__file__)

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(screenshot_each_action=False)
```

the bug info is 
```
Traceback (most recent call last):
  File "/Users/HGI/Program/projects/appCrawl/main.py", line 8, in <module>
    poco = AndroidUiautomationPoco(screenshot_each_action=False)
  File "/Users/HGI/Program/env3/lib/python3.8/site-packages/poco/drivers/android/uiautomation.py", line 170, in __init__
    self.ime.start()
  File "/Users/HGI/Program/env3/lib/python3.8/site-packages/airtest/core/android/ime.py", line 77, in start
    self.adb.shell("ime enable %s" % self.service_name)
  File "/Users/HGI/Program/env3/lib/python3.8/site-packages/airtest/core/android/adb.py", line 361, in shell
    out = self.raw_shell(cmd)
  File "/Users/HGI/Program/env3/lib/python3.8/site-packages/airtest/core/android/adb.py", line 319, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/Users/HGI/Program/env3/lib/python3.8/site-packages/airtest/core/android/adb.py", line 177, in cmd
    if re.search(DeviceConnectionError.DEVICE_CONNECTION_ERROR, stderr):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

```

How to fix that?
