### ISSUE TITLE
minitouch安装超时问题

### ISSUE THREAD

**Issue by wurijie** [AirtestProject/AirtestIDE#887]
* 测试开发环境AirtestIDE使用问题（本软件）

**详细描述问题bug：**
手机上minitouch_server正常启动，但airtestIDE中报错setup 超时

**复现步骤：**
特殊机型会出现，mumu模拟器正常

**python 版本:** `python3.x`

**操作系统:** `Mac、Windows、Centos都会出现`

**手机设备信息:**
 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]

**其他相关信息补充**
- AirtestIDE版本号：1.2.6

**截屏**
[09:46:58][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:7555 shell /data/local/tmp/minitouch -n 'minitouch_12289' 2>&1
[09:46:58][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'libevdev error in fix_invalid_absinfo: BUG: Device "Game China Virtual Input Device.0" has invalid ABS_MT_TRACKING_ID rangeType A touch device Game China Virtual Input Device.0 (720x1280 with 65536 contacts) detected on /dev/input/event0 (score 20960)'
[09:46:58][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: hard-limiting maximum number of contacts to 10'

======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest/cli/runner.py", line 73, in runTest
  File "site-packages/six.py", line 703, in reraise
  File "airtest/cli/runner.py", line 70, in runTest
  File "/Users/wurijie/CodeSync/airtest/test.air/test.py", line 9, in <module>
    dev.swipe_along([[148, 528],[366, 533],[573, 533],[366, 742],[154, 960],[357, 954],[579, 958]])
  File "airtest/core/android/android.py", line 439, in swipe_along
  File "airtest/core/android/touch_methods/touch_proxy.py", line 72, in swipe_along
  File "airtest/utils/snippet.py", line 105, in ready_func
  File "airtest/utils/snippet.py", line 115, in wrapper
  File "airtest/core/android/touch_methods/base_touch.py", line 42, in install_and_setup
  File "airtest/core/android/touch_methods/minitouch.py", line 94, in setup_server
RuntimeError: minitouch setup timeout

**问题出现原因分析**
1.手机上minitouch正常启动，但输出的的内容中：带Type关键字所在行，与上一个报错行连在一起了
2.airtestIDE上minitouch服务启动检测判断方法: 
/airtest/core/android/touch_methods/minitouch.py 99行
re.match("Type \w touch device .+ \((\d+)x(\d+) with \d+ contacts\) detected on .+ \(.+\)", line)，由于使用的match方法只会从行头第一个字符开始匹配，故导致匹配失败setup 超时，建议改成search方法，谢谢！

**Comment by yimelia** [comment]
感谢反馈，这个问题已经在测试分支dev上面修复了，将在1.1.7版本放出，请等待版本更新即可
