### ISSUE TITLE
更新 1.2.7 后无法识别 Windows 窗口

### ISSUE THREAD

**Issue by boylikesgirl** [AirtestProject/AirtestIDE#905]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 控件识别、树状结构、poco 库报错 -> https://github.com/AirtestProject/Poco/issues

**详细描述问题 bug：**
旧版 1.2.6 升级 1.2.7 后，再次识别 Windows 窗口无法正确识别。相比 1.2.6 版本，1.2.7 版本在命令行界面多了窗口识别的 LOG （*改过窗口识别相关？*）。
尝试过部分方法（管理员运行、兼容模式运行.bat）均未改善。

**复现步骤：**
1. 下载新版并打开
2. 尝试搜索窗口或识别所有窗口
3. 命令行显示如下：
 ```cmd
Traceback (most recent call last):
  File "app\plugins\devicepool\windows\panel.py", line 180, in _show_windows_table
  File "app\plugins\devicepool\windows\panel.py", line 97, in get_top_windows
  File "app\plugins\devicepool\windows\device.py", line 54, in find_all_window
pywintypes.error: (0, 'EnumChildWindows', 'No error message is available')
```

**Python 版本:** `python3.7` 
**Python 路径：** `C:\ProgramData\Anaconda3\Python.exe`
**操作系统:** `Windows10 64bit`
**使用设备** `惠普暗夜精灵 5 - 鼓包版`

**其他相关信息补充**
- AirtestIDE 版本号：1.2.6 & 1.2.7

**截屏**
强烈建议带上截图，包括 IDE 本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
图示以 Windows 的 Explorer 为例进行窗口识别（会看不到鼠标，但是鼠标确实在 Explorer 上）：
[1.2.6 正常](https://raw.githubusercontent.com/boylikesgirl/about-lenovo-optimizer/master/Windows%20%E7%AA%97%E5%8F%A3%E8%AF%86%E5%88%AB%E6%8A%A5%E9%94%99%20-%201.2.6%20-%20OK.png)
[1.2.7 异常](https://raw.githubusercontent.com/boylikesgirl/about-lenovo-optimizer/master/Windows%20%E7%AA%97%E5%8F%A3%E8%AF%86%E5%88%AB%E6%8A%A5%E9%94%99%20-%201.2.7%20-%20NG.png)

**Comment by daboluotou** [comment]
我也是windows连不上早知道不更新了 更新了个bug

**Comment by Lisa979** [comment]
更新后“选择游戏画面”和“搜索窗口”都不能用了
报错信息：
Traceback (most recent call last):
  File "app\plugins\devicepool\windows\panel.py", line 58, in mouseMoveEvent
  File "app\plugins\devicepool\windows\device.py", line 64, in find_window
  File "app\plugins\devicepool\windows\device.py", line 54, in find_all_window
pywintypes.error: (0, 'EnumChildWindows', 'No error message is available')
Sentry SDK with an error: ClientExceptionIgnored(The queue of sending trace is full, maybe you should adjust queue_size)
["error: (0, 'EnumChildWindows', 'No error message is available')", '  File "app\\plugins\\devicepool\\windows\\panel.py", line 58, in mouseMoveEvent', '  File "app\\plugins\\devicepool\\windows\\device.py", line 64, in find_window', '  File "app\\plugins\\devicepool\\windows\\device.py", line 54, in find_all_window']
**app\plugins文件夹下没有devicepool文件夹**
![image](https://user-images.githubusercontent.com/38977692/108591247-b005d300-73a2-11eb-8fad-9e9de7b959d8.png)
