### ISSUE TITLE
Error with BSTestRunner after updating 1.2.7 version

### ISSUE THREAD

**Issue by 0mvwromwwsz72ax** [AirtestProject/AirtestIDE#907]
I use [BSTestRunner](https://github.com/hongduhong/HTMLTestRunner-BSTestRunner) in my Airtest scripts.
Example:
```
from airtest.core.api import *
from datetime import datetime
import inspect, os, sys, time, shutil, unittest, BSTestRunner
time_day_now = datetime.today().strftime("%Y.%m.%d")
time_hour_now = datetime.today().strftime("%H-%M-%S")

dir1 = r"C:\Airtest\project"
try:
    os.makedirs(dir1 + "\\" + time_day_now + r"\02_01")
except:
    pass
dir2 = (dir1 + "\\" + time_day_now + r"\02_01")
dir3 = str(time_hour_now) + "_report.html"
fp = open(os.path.join(dir2, dir3), "wb")

if __name__ == '__main__':
    BSTestRunner.main()

class MyTests(unittest.TestCase):
    def first_test(self):
        try:
            time.sleep(1)
            assert True
            print('Success')
        except:
            print('Error')
            assert False

suite = unittest.TestLoader().loadTestsFromTestCase(MyTests)
runner = BSTestRunner.BSTestRunner(
            stream=fp,
            title='text1',
            description='text2')

runner.STYLESHEET_TMPL = '<link rel="stylesheet" href="my_stylesheet.css" type="text/css">'
def suite():
    suite = unittest.TestSuite()
    suite.addTest(MyTests('first_test'))
    
    return suite

suite = suite()

# run the test
runner.run(suite)
```
Now, after updating i have this error:
```
Traceback (most recent call last):
  File "C:\py\lib\site-packages\airtest\cli\runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "C:\Airtest\untitled.air\untitled.py", line 18, in <module>
    BSTestRunner.main()
  File "C:\py\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\py\lib\unittest\main.py", line 133, in parseArgs
    self._main_parser.parse_args(argv[1:], self)
  File "C:\py\lib\argparse.py", line 1821, in parse_args
    self.error(msg % ' '.join(argv))
  File "C:\py\lib\argparse.py", line 2575, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\py\lib\argparse.py", line 2562, in exit
    _sys.exit(status)
SystemExit: 2 
```

**AirtestIDE version:** `1.2.7`
**Platform:** `Windows10 64bit Pro.`
Please help

**Comment by xyl00755** [comment]
Have you ever get a solotion?
I use the unittest suite and get same error.

**Comment by 0mvwromwwsz72ax** [comment]
> Have you ever get a solotion?
> I use the unittest suite and get same error.

No. Just using 1.2.6 version

**Comment by yimelia** [comment]
hi @0mvwromwwsz72ax  @xyl00755 
AirtestIDE does not support scripts using unittest, so you can use the local python to run after deploying the python+airtest environment locally, see https://airtest.doc.io.netease.com/en/IDEdocs/run_script/1_useCommand_runScript/#2-run-the-script-using-the-local-python-environment
