### ISSUE TITLE
Airtest IDE1.2.9连接iphone7失败

### ISSUE THREAD

**Issue by 928874125** [AirtestProject/AirtestIDE#959]
xcode12.5
ipone7 ProductVersion: 13.1.2

AirtestIDE.EXE报这个错：

loading config from : C:\Users\Administrator\AppData\Local\AirtestIDE\AirtestIDE\user.json
try loading plugin: firebase_plugin
plugin loaded: firebase_plugin
try loading plugin: headspin_plugin
plugin loaded: headspin_plugin
try loading plugin: selenium_plugin
plugin loaded: selenium_plugin
[15:02:10][DEBUG]<airtest.core.android.adb> C:\YFVE_AT_Conf\AirtestIDE-win-1.2.8\airtest\core\android\static\adb\windows\adb.exe devices
[15:02:15][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\devicepool\abstract\device.py", line 82, in run
  File "app\plugins\devicepool\ios\device.py", line 81, in connect
  File "C:\YFVE_AT_Conf\AirtestIDE-win-1.2.8\airtest\core\ios\ios.py", line 211, in display_info
    self._display_info()
  File "C:\YFVE_AT_Conf\AirtestIDE-win-1.2.8\airtest\core\ios\ios.py", line 221, in _display_info
    snapshot = self.snapshot()
  File "C:\YFVE_AT_Conf\AirtestIDE-win-1.2.8\airtest\core\ios\ios.py", line 34, in wrapper
    return func(self, *args, **kwargs)
  File "C:\YFVE_AT_Conf\AirtestIDE-win-1.2.8\airtest\core\ios\ios.py", line 289, in snapshot
    data = self._neo_wda_screenshot()  # wda 截图不用考虑朝向
  File "C:\YFVE_AT_Conf\AirtestIDE-win-1.2.8\airtest\core\ios\ios.py", line 268, in _neo_wda_screenshot
    value = self.driver.http.get('screenshot').value
  File "site-packages\wda\utils.py", line 47, in _inner
  File "site-packages\wda\__init__.py", line 454, in _fetch
  File "site-packages\wda\__init__.py", line 124, in httpdo
  File "site-packages\wda\__init__.py", line 180, in _unsafe_httpdo
wda.exceptions.WDAUnknownError: WDARequestError(status=110, value={'error': 'unknown error', 'message': '-[XCUIScreen screenshotDataForQuality:rect:error:]: unrecognized selector sent to instance 0x28161cf40'})

**Comment by 928874125** [comment]
是什么问题？
