### ISSUE TITLE
oppo和vivo已经默认了Yosemite输入法还是会报AdbShellError这个错误

### ISSUE THREAD

**Issue by sorrykint** [AirtestProject/AirtestIDE#988]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
bug描述
oppo和vivo已经默认了Yosemite输入法还是会报AdbShellError这个错误
**复现步骤：**
使用start_app('con.tencent.mm')就会报错

**python 版本:** `python3.x`

**操作系统:** `Windows7 64bit`

**手机设备信息:**
 - 手机型号:
 - oppo Reno3 pro 
 - vivo NEX A
 - 
 - Android系统版本号: [e.g. Android 8.1]
 - Android10
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：

**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。
Traceback (most recent call last):
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\android\adb.py", line 374, in shell
    out = self.raw_shell(cmd)
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\android\adb.py", line 332, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\android\adb.py", line 197, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b'  bash arg: -p\r\n  bash arg: con.tencent.mm\r\n  bash arg: -c\r\n  bash arg: android.intent.category.LAUNCHER\r\n  bash arg: 1\r\n** No activities found to run, monkey aborted.\r\n'] stderr[b'args: [-p, con.tencent.mm, -c, android.intent.category.LAUNCHER, 1]\r\n arg: "-p"\r\n arg: "con.tencent.mm"\r\n arg: "-c"\r\n arg: "android.intent.category.LAUNCHER"\r\n arg: "1"\r\ndata="con.tencent.mm"\r\ndata="android.intent.category.LAUNCHER"\r\n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/vhvmj/PycharmProjects/Pocotext/poco/Login.py", line 57, in <module>
    twDomeStart()
  File "C:/Users/vhvmj/PycharmProjects/Pocotext/poco/Login.py", line 48, in twDomeStart
    start_app('con.tencent.mm')
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\utils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\api.py", line 183, in start_app
    G.DEVICE.start_app(package, activity)
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\android\android.py", line 307, in start_app
    return self.adb.start_app(package, activity)
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\android\adb.py", line 1233, in start_app
    self.shell(['monkey', '-p', package, '-c', 'android.intent.category.LAUNCHER', '1'])
  File "C:\Users\vhvmj\PycharmProjects\Pocotext\venv\lib\site-packages\airtest\core\android\adb.py", line 376, in shell
    raise AdbShellError(err.stdout, err.stderr)
airtest.core.error.AdbShellError: stdout[b'  bash arg: -p\r\n  bash arg: con.tencent.mm\r\n  bash arg: -c\r\n  bash arg: android.intent.category.LAUNCHER\r\n  bash arg: 1\r\n** No activities found to run, monkey aborted.\r\n'] stderr[b'args: [-p, con.tencent.mm, -c, android.intent.category.LAUNCHER, 1]\r\n arg: "-p"\r\n arg: "con.tencent.mm"\r\n arg: "-c"\r\n arg: "android.intent.category.LAUNCHER"\r\n arg: "1"\r\ndata="con.tencent.mm"\r\ndata="android.intent.category.LAUNCHER"\r\n']
[11:12:14][DEBUG]<airtest.core.android.adb> C:\Users\vhvmj\PycharmProjects\Pocotext\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 98795786 forward --remove tcp:11215

Process finished with exit code 1

**Comment by yimelia** [comment]
log里说了，错误原因是：No activities found to run, monkey aborted.
