### ISSUE TITLE
进入部分app的登录界面自动断连

### ISSUE THREAD

**Issue by zpywj99001** [AirtestProject/AirtestIDE#991]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。**否则直接关闭。**)

**(重要！根据问题类型选择分类)**
* 测试开发环境AirtestIDE使用问题（本软件） -> 本页面

**详细描述问题bug：**
部分app（如饿了么、喜马拉雅）进入登录页面时，IDE自动断开连接

**复现步骤：**
打开【饿了么】APP，根据首页提示点击【马上登陆】。

**python 版本:** `python3.x`

**操作系统:** `Windows10 64bit`

**手机设备信息:**
 - 手机型号:小米10s
 - Android系统版本号: Android 11
 - MIUI 12.5.7

**其他相关信息补充**
PC配置信息：
Intel (R) Celeron(R) CPU G530 @ 2.40GHz
内存：8GB

- AirtestIDE版本号：1.2.9

**截屏**
附上IDE相关日志
[touch init] begin
[17:43:45][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell dumpsys package com.netease.nie.yosemite
[17:43:45][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 forward --no-rebind tcp:13520 localabstract:javacap_13520
[17:43:46][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell pm path com.netease.nie.yosemite
[17:43:46][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell ls -l /data/local/tmp/maxpresent.jar
[17:43:46][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell CLASSPATH=/data/app/~~j1VQnCCQOY_gN9PBeEKkcg==/com.netease.nie.yosemite-VbE-dsKGV-dSh-FM3OSFjQ==/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_13520 -lazy 2>&1
[17:43:47][DEBUG]<airtest.core.android.touch_methods.maxtouch> install_minitouch skipped
[17:43:47][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[17:43:47][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_13520'
[17:43:47][DEBUG]<airtest.core.android.javacap> (1, 3, 0, 1080, 2340, 0, 0, 0, 1)
[17:43:47][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell dumpsys window displays
[17:43:47][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 forward --no-rebind tcp:13336 localabstract:maxpresent_13336
[17:43:47][DEBUG]<airtest.core.android.adb> E:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 192.168.0.5:10000 shell app_process -Djava.class.path=/data/local/tmp/maxpresent.jar /data/local/tmp com.netease.maxpresent.MaxPresent socket maxpresent_13336
[17:43:48][DEBUG]<airtest.utils.nbsp> [airtouch_server]b'Metrics Message : 2340.0=====1080.0'
[touch init] finished
[17:43:48][DEBUG]<airtest.utils.nbsp> [airtouch_server]b'Start local socket (maxpresent_13336) server...'
[17:44:18][DEBUG]<airtest.utils.nbsp> [javacap_sever]b''
[17:44:18][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\devicepool\android\device.py", line 378, in run
  File "app\plugins\devicepool\android\device.py", line 387, in main_loop
  File "airtest\core\android\javacap.py", line 103, in get_frame_from_stream
    return self.frame_gen.send(None)
  File "airtest\utils\threadsafe.py", line 27, in send
    return self.it.send(*args)
StopIteration

[Warning] The current device is unplugged!

**Comment by 361028096** [comment]
请问有解决办法吗？

**Comment by wangdayecoding** [comment]
小米10也有

**Comment by yimelia** [comment]
根据文档：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#2
修改一下手机的设置，一般都是一些例如“安全键盘”这样的设置导致手机阻止了截图
